# Auto-generated from Python examples and PTA test suites.
# Commands found in real automation scripts get a relevance boost
# so they rank higher in keyword search results.
# Source: 23 Python files, 266 total SCPI calls
# Unique commands: 134

_USAGE_BOOSTS: dict[str, int] = {
    "ACQUIRE:STATE": 50,  # 15x in examples
    "*OPC": 50,  # 14x in examples
    "*IDN": 50,  # 11x in examples
    "DISPLAY:WAVEVIEW<x>:CH<x>:STATE": 50,  # 9x in examples
    "ACQUIRE:STOPAFTER": 50,  # 6x in examples
    "*RST": 50,  # 5x in examples
    "DISPLAY:WAVEVIEW<x>:CH3_D<x>:STATE": 50,  # 5x in examples
    "HORIZONTAL:SCALE": 50,  # 5x in examples
    "TRIGGER:A:EDGE:SOURCE": 50,  # 5x in examples
    "TRIGGER:A:EDGE:SLOPE": 50,  # 5x in examples
    "FILESYSTEM:READFILE": 25,  # 4x in examples
    "DISPLAY:WAVEFORM": 25,  # 4x in examples
    "HEADER": 25,  # 4x in examples
    "DISPLAY:WAVEVIEW<x>:REF<x>:STATE": 25,  # 4x in examples
    "HORIZONTAL:POSITION": 25,  # 4x in examples
    "TRIGGER:A:LEVEL:CH<x>": 25,  # 4x in examples
    "MEASUREMENT:DELETEALL": 25,  # 4x in examples
    "SAVE:IMAGE": 25,  # 3x in examples
    "MEASUREMENT:MEAS<x>:TYPE": 25,  # 3x in examples
    "MEASUREMENT:MEAS<x>:SOURCE<x>": 25,  # 3x in examples
    "MEASUREMENT:MEAS<x>:STATE": 25,  # 3x in examples
    "TRIGGER:A:MODE": 25,  # 3x in examples
    "EDGE": 25,  # 3x in examples
    "CH<x>:TERMINATION": 25,  # 3x in examples
    "CH<x>:SCALE": 25,  # 3x in examples
    "CH<x>:OFFSET": 25,  # 3x in examples
    "ACQUIRE:MODE": 25,  # 3x in examples
    "MEASUREMENT:MEAS<x>:RESULTS:ALLACQS:POPULATION": 25,  # 3x in examples
    "COMMANDS": 25,  # 2x in examples
    "COMMAND:": 25,  # 2x in examples
    "GROUP:": 25,  # 2x in examples
    "INVALID": 25,  # 2x in examples
    "*CLS": 25,  # 2x in examples
    "SV:SPAN": 25,  # 2x in examples
    "MEASUREMENT:MEAS<x>:CLEAR": 25,  # 2x in examples
    "AMPLITUDE": 25,  # 2x in examples
    "RECALL:WAVEFORM": 25,  # 2x in examples
    "TRIGGER:A:TYPE": 25,  # 2x in examples
    "MEASUREMENT:ADDNEW": 25,  # 2x in examples
    "MEASUREMENT:<x>:SOURCE<x>": 25,  # 2x in examples
    "MEASUREMENT:<x>:DELAY:EDGE<x>": 25,  # 2x in examples
    "CLEAR": 25,  # 2x in examples
    "MEASUREMENT:MEAS<x>:SOURCE": 25,  # 2x in examples
    "FILESYSTEM:DELETE": 25,  # 2x in examples
    "MEASUREMENT:MEAS<x>:DELAY:EDGE<x>": 25,  # 2x in examples
    "MEASUREMENT:MEAS<x>:RESULTS:CURRENTACQ:MEAN": 25,  # 2x in examples
    "MATH:MATH<x>:SOURCE<x>": 25,  # 2x in examples
    "LOADSCRIPT": 10,  # 1x in examples
    "ENDSCRIPT": 10,  # 1x in examples
    "BENCHMARK": 10,  # 1x in examples
    "TOTAL:": 10,  # 1x in examples
    "THESE": 10,  # 1x in examples
    "THEY": 10,  # 1x in examples
    "ARGUMENTS:": 10,  # 1x in examples
    "EXAMPLES:": 10,  # 1x in examples
    "ENHANCED": 10,  # 1x in examples
    "OPTIONS:": 10,  # 1x in examples
    "SOURCE:": 10,  # 1x in examples
    "COMMAND": 10,  # 1x in examples
    "TOTAL": 10,  # 1x in examples
    "DUPLICATES": 10,  # 1x in examples
    "AUTOSET": 10,  # 1x in examples
    "HORIZONTAL:ACQLENGTH": 10,  # 1x in examples
    "HORIZONTAL:FASTFRAME:COUNT": 10,  # 1x in examples
    "HORIZONTAL:FASTFRAME:STATE": 10,  # 1x in examples
    "SAVE:WAVEFORM:FILEFORMAT": 10,  # 1x in examples
    "SAVE:WAVEFORM:DATA:START": 10,  # 1x in examples
    "SAVE:WAVEFORM:DATA:STOP": 10,  # 1x in examples
    "DATA:FRAMESTART": 10,  # 1x in examples
    "DATA:FRAMESTOP": 10,  # 1x in examples
    "SAVE:WAVEFORM": 10,  # 1x in examples
    "MEASU:MEAS<x>:VAL": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:FAILCOUNT": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:STATUS": 10,  # 1x in examples
    "TRIG:A:LEVEL:CH<x>": 10,  # 1x in examples
    "SV:CH<x>:SELECT:RF_AVERAGE": 10,  # 1x in examples
    "SV:CH<x>:RF_AVERAGE:NUMAVG": 10,  # 1x in examples
    "SV:CH<x>:SELECT:RF_MAXHOLD": 10,  # 1x in examples
    "SV:MARKER:PEAK:STATE": 10,  # 1x in examples
    "SV:MARKER:PEAK:THRESHOLD": 10,  # 1x in examples
    "PEAKSTABLE:ADDNEW": 10,  # 1x in examples
    "SV:MARKER:PEAKS:FREQUENCY": 10,  # 1x in examples
    "SV:MARKER:PEAKS:AMPLITUDE": 10,  # 1x in examples
    "FILESYSTEM:CWD": 10,  # 1x in examples
    "TRIGGER:STATE": 10,  # 1x in examples
    "PLOT:PLOT<x>:TYPE": 10,  # 1x in examples
    "DISPLAY:SELECT:VIEW": 10,  # 1x in examples
    "SAVE:PLOTDATA": 10,  # 1x in examples
    "OFF": 10,  # 1x in examples
    "SAMPLE": 10,  # 1x in examples
    "SEQUENCE": 10,  # 1x in examples
    "MAXIMUM": 10,  # 1x in examples
    "PERIOD": 10,  # 1x in examples
    "PDUTY": 10,  # 1x in examples
    "RISETIME": 10,  # 1x in examples
    "ACRMS": 10,  # 1x in examples
    "SINGLE": 10,  # 1x in examples
    "EXECUTE": 10,  # 1x in examples
    "NORMAL": 10,  # 1x in examples
    "FREQUENCY": 10,  # 1x in examples
    "SPI": 10,  # 1x in examples
    "ONE": 10,  # 1x in examples
    "RIS": 10,  # 1x in examples
    "FALL": 10,  # 1x in examples
    "BUS": 10,  # 1x in examples
    "DATA": 10,  # 1x in examples
    "SEQ": 10,  # 1x in examples
    "CH<x>:COUPLING": 10,  # 1x in examples
    "CH<x>:BANDWIDTH": 10,  # 1x in examples
    "TRIGGER:A:LEVEL:<x>": 10,  # 1x in examples
    "MEASUREMENT:<x>:TYPE": 10,  # 1x in examples
    "MEASUREMENT:<x>:SOURCE": 10,  # 1x in examples
    "MEASUREMENT:<x>:STATE": 10,  # 1x in examples
    "MEASUREMENT:<x>:DISPLAYSTAT:ENABLE": 10,  # 1x in examples
    "MEASUREMENT:<x>:POPULATION:LIMIT:STATE": 10,  # 1x in examples
    "MEASUREMENT:<x>:POPULATION:LIMIT:VALUE": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:RESULTS:ALLACQS:MEAN": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:RESULTS:ALLACQS:STDDEV": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:DISPLAYSTAT:ENABLE": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:POPULATION:LIMIT:STATE": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:POPULATION:LIMIT:VALUE": 10,  # 1x in examples
    "CH{CH1}:SCALE": 10,  # 1x in examples
    "CH{CH1}:OFFSET": 10,  # 1x in examples
    "CH{CH1}:TERMINATION": 10,  # 1x in examples
    "CH{CH2}:SCALE": 10,  # 1x in examples
    "CH{CH2}:OFFSET": 10,  # 1x in examples
    "CH{CH2}:TERMINATION": 10,  # 1x in examples
    "MEASUREMENT:ADDMEAS": 10,  # 1x in examples
    "MATH:ADDNEW": 10,  # 1x in examples
    "MATH:MATH<x>:TYPE": 10,  # 1x in examples
    "MATH:MATH<x>:FUNCTION": 10,  # 1x in examples
    "DISPLAY:WAVEVIEW<x>:MATH:MATH<x>:STATE": 10,  # 1x in examples
    "DISPLAY:WAVEVIEW<x>:MATH:MATH<x>:VERTICAL:SCALE": 10,  # 1x in examples
    "MEASUREMENT:MEAS<x>:PATTERNDETECTION": 10,  # 1x in examples
}