"""
Command-to-Group Mapping for DPO Series
Generated from Command_groups_DPOx.txt
"""

COMMAND_TO_GROUP = {
    "ACQuire:ENHANCEDEnob": "Acquisition",
    "ACQuire:INTERPEightbit": "Acquisition",
    "ACQuire:MAGnivu": "Acquisition",
    "ACQuire:MODe": "Acquisition",
    "ACQuire:MODe:ACTUal": "Acquisition",
    "ACQuire:MODe:ACTUal?": "Acquisition",
    "ACQuire:NUMACq": "Acquisition",
    "ACQuire:NUMACq?": "Acquisition",
    "ACQuire:NUMAVg": "Acquisition",
    "ACQuire:NUMEnv": "Acquisition",
    "ACQuire:NUMFRAMESACQuired": "Acquisition",
    "ACQuire:NUMFRAMESACQuired?": "Acquisition",
    "ACQuire:NUMSAMples": "Acquisition",
    "ACQuire:SAMPlingmode": "Acquisition",
    "ACQuire:STATE": "Acquisition",
    "ACQuire:STOPAfter": "Acquisition",
    "ALIas:CATalog": "Alias",
    "ALIas:CATalog?": "Alias",
    "ALIas:DEFine": "Alias",
    "ALIas:DELEte": "Alias",
    "ALIas:DELEte:ALL": "Alias",
    "ALIas:DELEte:NAMe": "Alias",
    "ALIas:STATE": "Alias",
    "ALLOcate:WAVEform:REF<x>": "Waveform Transfer",
    "ALLOcate:WAVEform:REF<x>?": "Waveform Transfer",
    "APPLication:ACTivate": "Miscellaneous",
    "AUXIn:BANdwidth": "Vertical",
    "AUXIn:COUPling": "Vertical",
    "AUXIn:OFFSet": "Vertical",
    "AUXIn:PROBEFunc:EXTAtten": "Vertical",
    "AUXIn:PROBEFunc:EXTDBatten": "Vertical",
    "AUXIn:PROBEFunc:EXTUnits": "Vertical",
    "AUXIn:PRObe:AUTOZero": "Vertical",
    "AUXIn:PRObe:DEGAUSS": "Vertical",
    "AUXIn:PRObe:GAIN": "Vertical",
    "AUXIn:PRObe:GAIN?": "Vertical",
    "AUXIn:PRObe:ID:SERnumber": "Vertical",
    "AUXIn:PRObe:ID:SERnumber?": "Vertical",
    "AUXIn:PRObe:ID:TYPe": "Vertical",
    "AUXIn:PRObe:ID:TYPe?": "Vertical",
    "AUXIn:PRObe:INPUTMode": "Vertical",
    "AUXIn:PRObe:INPUTMode:BOFFSet": "Vertical",
    "AUXIn:PRObe:INPUTMode:CMOFFSet": "Vertical",
    "AUXIn:PRObe:INPUTMode:DMOFFSet": "Vertical",
    "AUXIn:PRObe:RANge": "Vertical",
    "AUXIn:PRObe:RESistance": "Vertical",
    "AUXIn:PRObe:RESistance?": "Vertical",
    "AUXIn:PRObe:SET": "Vertical",
    "AUXIn:PRObe:SIGnal": "Vertical",
    "AUXIn:PRObe:TIPtype": "Vertical",
    "AUXIn:PRObe:UNIts": "Vertical",
    "AUXIn:PRObe:UNIts?": "Vertical",
    "AUXIn:VTERm:DUAL:A": "Vertical",
    "AUXIn:VTERm:DUAL:B": "Vertical",
    "AUXout:EDGE": "Miscellaneous",
    "AUXout:SOUrce": "Miscellaneous",
    "BUS:B1<x>:DISplay:HIERarchical": "Bus",
    "BUS:B1<x>:USB:HYSTeresis": "Bus",
    "BUS:B<x>:CAN:BITRate": "Bus",
    "BUS:B<x>:CAN:BITRate:VALue": "Bus",
    "BUS:B<x>:CAN:PRObe": "Bus",
    "BUS:B<x>:CAN:SOUrce": "Bus",
    "BUS:B<x>:DISplay:DECOde:STAte": "Bus",
    "BUS:B<x>:ETHERnet:SOUrce:DPLUs": "Bus",
    "BUS:B<x>:ETHERnet:TYPe": "Bus",
    "BUS:B<x>:FLEXRAY:BITRate": "Bus",
    "BUS:B<x>:FLEXRAY:BITRate:VALue": "Bus",
    "BUS:B<x>:FLEXRAY:SOUrce": "Bus",
    "BUS:B<x>:I2C:RWINADDR": "Bus",
    "BUS:B<x>:LABel": "Bus",
    "BUS:B<x>:LIN:BITRate": "Bus",
    "BUS:B<x>:LIN:BITRate:VALue": "Bus",
    "BUS:B<x>:LIN:IDFORmat": "Bus",
    "BUS:B<x>:LIN:POLarity": "Bus",
    "BUS:B<x>:LIN:SOUrce": "Bus",
    "BUS:B<x>:LIN:STANDard": "Bus",
    "BUS:B<x>:MIL1553B:POLarity": "Bus",
    "BUS:B<x>:MIPICSITWo:LANE<x>:TYPe": "Bus",
    "BUS:B<x>:MIPIDSIOne:LANE<x>:TYPe": "Bus",
    "BUS:B<x>:PARallel:CLOCk:SOUrce": "Bus",
    "BUS:B<x>:PCIE:BITRate": "Bus",
    "BUS:B<x>:PCIE:BITRate:VALue": "Bus",
    "BUS:B<x>:PCIE:HYSTeresis": "Bus",
    "BUS:B<x>:PCIE:LANE": "Bus",
    "BUS:B<x>:PCIE:SOUrce": "Bus",
    "BUS:B<x>:POSition": "Bus",
    "BUS:B<x>:RS232C:BITRate": "Bus",
    "BUS:B<x>:RS232C:DATABits": "Bus",
    "BUS:B<x>:RS232C:POLarity": "Bus",
    "BUS:B<x>:RS232C:SOUrce": "Bus",
    "BUS:B<x>:S8B10B:BITRate:VALue": "Bus",
    "BUS:B<x>:S8B10B:HYSTeresis": "Bus",
    "BUS:B<x>:S8B10B:SOUrce": "Bus",
    "BUS:B<x>:SPI:BITOrder": "Bus",
    "BUS:B<x>:SPI:CLOCk:POLarity": "Bus",
    "BUS:B<x>:SPI:DATa:SIZe": "Bus",
    "BUS:B<x>:SPI:DATa:SOUrce": "Bus",
    "BUS:B<x>:SPI:FRAMING": "Bus",
    "BUS:B<x>:SPI:IDLETime": "Bus",
    "BUS:B<x>:SPI:SELect:POLarity": "Bus",
    "BUS:B<x>:USB:BITRate": "Bus",
    "BUS:B<x>:USB:PRObe": "Bus",
    "BUS:B<x>:USB:SOUrce": "Bus",
    "BUS:CH<x>:THRESHold": "Bus",
    "BUS:MATH<x>:LOWTHRESHold": "Bus",
    "BUS:MATH<x>:THRESHold": "Bus",
    "BUS:REF<x>:THRESHold": "Bus",
    "CALibrate:CALProbe:CH<x>": "Calibration",
    "CALibrate:CALProbe:CH<x>?": "Calibration",
    "CALibrate:INTERNal": "Calibration",
    "CALibrate:INTERNal:STARt": "Calibration",
    "CALibrate:PRObestate:CH<x>": "Calibration",
    "CALibrate:PRObestate:CH<x>?": "Calibration",
    "CALibrate:RESults:SPC": "Calibration",
    "CALibrate:RESults:SPC?": "Calibration",
    "CH<x>:ATIACTive": "Vertical",
    "CH<x>:ATIACTive?": "Vertical",
    "CH<x>:AVAILable": "Vertical",
    "CH<x>:AVAILable?": "Vertical",
    "CH<x>:BANdwidth": "Vertical",
    "CH<x>:BANdwidth:ENHanced:APPLYtoall": "Vertical",
    "CH<x>:BANdwidth:ENHanced:FORCe": "Vertical",
    "CH<x>:COUPling": "Vertical",
    "CH<x>:DESKew": "Vertical",
    "CH<x>:FASTAcqcapable": "Vertical",
    "CH<x>:FASTAcqcapable?": "Vertical",
    "CH<x>:ICAPture:SOUrce": "Vertical",
    "CH<x>:ICAPture:STATE": "Vertical",
    "CH<x>:LABel:NAMe": "Vertical",
    "CH<x>:LABel:XPOS": "Vertical",
    "CH<x>:LABel:YPOS": "Vertical",
    "CH<x>:OFFSet": "Vertical",
    "CH<x>:POSition": "Vertical",
    "CH<x>:PROBECOntrol": "Vertical",
    "CH<x>:PROBECal": "Vertical",
    "CH<x>:PROBECal?": "Vertical",
    "CH<x>:PROBEFunc:EXTAtten": "Vertical",
    "CH<x>:PROBEFunc:EXTDBatten": "Vertical",
    "CH<x>:PRObe": "Vertical",
    "CH<x>:PRObe:AUTOZero": "Vertical",
    "CH<x>:PRObe:DEGAUSS": "Vertical",
    "CH<x>:PRObe:GAIN": "Vertical",
    "CH<x>:PRObe:GAIN?": "Vertical",
    "CH<x>:PRObe:ID": "Vertical",
    "CH<x>:PRObe:ID:SERnumber": "Vertical",
    "CH<x>:PRObe:ID:SERnumber?": "Vertical",
    "CH<x>:PRObe:ID?": "Vertical",
    "CH<x>:PRObe:INPUTMode": "Vertical",
    "CH<x>:PRObe:INPUTMode:AOFFSet": "Vertical",
    "CH<x>:PRObe:INPUTMode:BOFFSet": "Vertical",
    "CH<x>:PRObe:INPUTMode:CMOFFSet": "Vertical",
    "CH<x>:PRObe:INPUTMode:DMOFFSet": "Vertical",
    "CH<x>:PRObe:RANge": "Vertical",
    "CH<x>:PRObe:RESistance": "Vertical",
    "CH<x>:PRObe:RESistance?": "Vertical",
    "CH<x>:PRObe:SET": "Vertical",
    "CH<x>:PRObe:SIGnal": "Vertical",
    "CH<x>:PRObe:TIPtype": "Vertical",
    "CH<x>:PRObe:UNIts": "Vertical",
    "CH<x>:PRObe:UNIts?": "Vertical",
    "CH<x>:PRObe?": "Vertical",
    "CH<x>:SCAle": "Vertical",
    "CH<x>:TERmination": "Vertical",
    "CH<x>:THRESHold": "Vertical",
    "CH<x>:VTERm:BIAS": "Vertical",
    "CH<x>:VTERm:DUAL:A": "Vertical",
    "CH<x>:VTERm:DUAL:B": "Vertical",
    "CLEAR zeroes the frame error results ERRORDetector:FRAme:TEST:BADCHARS": "Error Detector",
    "CLEAR zeroes the frame error results ERRORDetector:FRAme:TEST:BADCHARS?": "Error Detector",
    "COUnter:DURation": "Trigger",
    "COUnter:GAIn": "Trigger",
    "COUnter:LOGAction": "Trigger",
    "COUnter:LOGNumber": "Trigger",
    "COUnter:LOGTable": "Trigger",
    "COUnter:REFerence": "Trigger",
    "COUnter:RESULTs": "Trigger",
    "COUnter:RESULTs:AVGmean": "Trigger",
    "COUnter:RESULTs:AVGmean?": "Trigger",
    "COUnter:RESULTs:DEViation": "Trigger",
    "COUnter:RESULTs:DEViation?": "Trigger",
    "COUnter:RESULTs:MAXimum": "Trigger",
    "COUnter:RESULTs:MAXimum?": "Trigger",
    "COUnter:RESULTs:MINimum": "Trigger",
    "COUnter:RESULTs:MINimum?": "Trigger",
    "COUnter:RESULTs:NUMber": "Trigger",
    "COUnter:RESULTs:NUMber?": "Trigger",
    "COUnter:RESULTs:VALue": "Trigger",
    "COUnter:RESULTs:VALue?": "Trigger",
    "COUnter:RESULTs?": "Trigger",
    "COUnter:SHOWLog": "Trigger",
    "COUnter:SHOWMeasurement": "Trigger",
    "COUnter:STAte": "Trigger",
    "COUnter:TYPe": "Trigger",
    "COUnter:UPDate": "Trigger",
    "COUnter:VIEW": "Trigger",
    "CQ<x>:THRESHold": "Digital",
    "CURSor:FUNCtion": "Cursor",
    "CURSor:HBArs": "Cursor",
    "CURSor:HBArs:DELTa": "Cursor",
    "CURSor:HBArs:DELTa?": "Cursor",
    "CURSor:HBArs?": "Cursor",
    "CURSor:LINESTyle": "Cursor",
    "CURSor:MODe": "Cursor",
    "CURSor:SCREEN:STYle": "Cursor",
    "CURSor:STATE": "Cursor",
    "CURSor:VBArs": "Cursor",
    "CURSor:VBArs:DELTa": "Cursor",
    "CURSor:VBArs:DELTa?": "Cursor",
    "CURSor:VBArs:UNIts": "Cursor",
    "CURSor:WAVEform": "Cursor",
    "CURSor:WAVEform:UNIts": "Cursor",
    "CURSor:XY:PRODDELta": "Cursor",
    "CURSor:XY:PRODDELta?": "Cursor",
    "CURSor:XY:PRODUCT<x>": "Cursor",
    "CURSor:XY:PRODUCT<x>?": "Cursor",
    "CURSor:XY:RATDELta": "Cursor",
    "CURSor:XY:RATDELta?": "Cursor",
    "CURSor:XY:RATIO<x>": "Cursor",
    "CURSor:XY:RATIO<x>?": "Cursor",
    "CURSor:XY:RDELta": "Cursor",
    "CURSor:XY:RDELta?": "Cursor",
    "CURSor:XY:READOUT": "Cursor",
    "CURSor:XY:RECTX<x>": "Cursor",
    "CURSor:XY:RECTY<x>": "Cursor",
    "CURSor:XY:THDELta": "Cursor",
    "CURSor:XY:THDELta?": "Cursor",
    "CURSor:XY:THETA<x>": "Cursor",
    "CURSor:XY:THETA<x>?": "Cursor",
    "CURSor:XY:XDELta": "Cursor",
    "CURSor:XY:XDELta?": "Cursor",
    "CURSor:XY:YDELta": "Cursor",
    "CURSor:XY:YDELta?": "Cursor",
    "D<x>:LABEL": "Digital",
    "D<x>:POSition": "Digital",
    "D<x>:PROBE:ID:TYPe": "Digital",
    "D<x>:PROBE:ID:TYPe?": "Digital",
    "D<x>:THRESHold": "Digital",
    "DATa:DESTination": "Waveform Transfer",
    "DATa:ENCdg": "Waveform Transfer",
    "DATa:FRAMESTARt": "Waveform Transfer",
    "DATa:FRAMESTOP": "Waveform Transfer",
    "DATa:SOUrce": "Waveform Transfer",
    "DATa:STARt": "Waveform Transfer",
    "DATa:STOP": "Waveform Transfer",
    "DATa:SYNCSOUrces": "Waveform Transfer",
    "DELEte:SETUp": "Save and Recall",
    "DELEte:WAVEform": "Save and Recall",
    "DIAg:CONTROL:HALT": "Diagnostics",
    "DIAg:CONTROL:LOOP": "Diagnostics",
    "DIAg:EXECUTE": "Diagnostics",
    "DIAg:FAILURES:CLEAR": "Diagnostics",
    "DIAg:ITEM": "Diagnostics",
    "DIAg:ITEM:FAILURES": "Diagnostics",
    "DIAg:ITEM:FAILURES?": "Diagnostics",
    "DIAg:ITEM:NAMe": "Diagnostics",
    "DIAg:ITEM:NAMe?": "Diagnostics",
    "DIAg:ITEM:RESULT": "Diagnostics",
    "DIAg:ITEM:RESULT?": "Diagnostics",
    "DIAg:ITEM:SUBITEMS": "Diagnostics",
    "DIAg:ITEM:SUBITEMS?": "Diagnostics",
    "DIAg:ITEM?": "Diagnostics",
    "DIAg:LEVEL": "Diagnostics",
    "DIAg:LOOPS": "Diagnostics",
    "DIAg:LOOPS?": "Diagnostics",
    "DIAg:NAMe": "Diagnostics",
    "DIAg:NAMe:AREA": "Diagnostics",
    "DIAg:NAMe:AREA?": "Diagnostics",
    "DIAg:NAMe:SUBSYS": "Diagnostics",
    "DIAg:NAMe:SUBSYS?": "Diagnostics",
    "DIAg:NAMe:TEST": "Diagnostics",
    "DIAg:NAMe:TEST?": "Diagnostics",
    "DIAg:NAMe?": "Diagnostics",
    "DIAg:NUMITEMS": "Diagnostics",
    "DIAg:NUMITEMS?": "Diagnostics",
    "DIAg:RESults": "Diagnostics",
    "DIAg:RESults?": "Diagnostics",
    "DIAg:SELect:ALL": "Diagnostics",
    "DIAg:SELect:AREA": "Diagnostics",
    "DIAg:SELect:LAST": "Diagnostics",
    "DIAg:SELect:SUBSYS": "Diagnostics",
    "DIAg:SELect:TEST": "Diagnostics",
    "DIAg:STATE": "Diagnostics",
    "DIAg:STOP": "Diagnostics",
    "DISplay:CLOCk": "Display control",
    "DISplay:COLOr": "Display control",
    "DISplay:COLOr:MATHCOLOr": "Display control",
    "DISplay:COLOr:PALEtte:USEr:HIStogram": "Display control",
    "DISplay:COLOr:PALEtte:USEr:MATH<x>": "Display control",
    "DISplay:COLOr?": "Display control",
    "DISplay:DIGital:HEIght": "Digital",
    "DISplay:FILTer": "Display control",
    "DISplay:FORMat": "Display control",
    "DISplay:GRAticule": "Display control",
    "DISplay:INTENSITy": "Display control",
    "DISplay:INTENSITy?": "Display control",
    "DISplay:PERSistence": "Display control",
    "DISplay:PERSistence:RESET": "Display control",
    "DISplay:SCREENTExt": "Display control",
    "DISplay:SCREENTExt:LABel<x>:FONTSIze": "Display control",
    "DISplay:SCREENTExt?": "Display control",
    "DISplay:SHOWREmote": "Display control",
    "DISplay:STYle": "Display control",
    "DISplay:TRIGBar": "Display control",
    "DISplay:TRIGT": "Display control",
    "DISplay:VARpersist": "Display control",
    "DISplay:WAVEform": "Display control",
    "EMail:ATTempts": "E-mail",
    "EMail:AUTHLogin": "E-mail",
    "EMail:AUTHPassword": "E-mail",
    "EMail:COUNt": "E-mail",
    "EMail:COUNt?": "E-mail",
    "EMail:FROm": "E-mail",
    "EMail:HOSTwanted": "E-mail",
    "EMail:IMAGe": "E-mail",
    "EMail:MASK": "E-mail",
    "EMail:MAXSize": "E-mail",
    "EMail:MEASUrement": "E-mail",
    "EMail:NUMEMails": "E-mail",
    "EMail:SMTPPort": "E-mail",
    "EMail:SMTPServer": "E-mail",
    "EMail:STATUS": "E-mail",
    "EMail:STATUS?": "E-mail",
    "EMail:TIMEOut": "E-mail",
    "EMail:TO": "E-mail",
    "EMail:TRIGger": "E-mail",
    "EMail:WAVEform": "E-mail",
    "ERRORDetector:ALERT": "Error Detector",
    "ERRORDetector:ALIGNCHARacter": "Error Detector",
    "ERRORDetector:ALIGNCHARacter?": "Error Detector",
    "ERRORDetector:ALIGNPRIMitive:PLUS<x>": "Error Detector",
    "ERRORDetector:ALIGNPRIMitive:PLUS<x>?": "Error Detector",
    "ERRORDetector:BIT:LENgth": "Error Detector",
    "ERRORDetector:BIT:SYNCPATtern:BITString": "Error Detector",
    "ERRORDetector:BIT:TEST": "Error Detector",
    "ERRORDetector:BIT:TEST:COUNt": "Error Detector",
    "ERRORDetector:BIT:TEST:COUNt?": "Error Detector",
    "ERRORDetector:BIT:TEST:RATE": "Error Detector",
    "ERRORDetector:BIT:TEST:RATE?": "Error Detector",
    "ERRORDetector:BIT:TEST:STATUS:START": "Error Detector",
    "ERRORDetector:BIT:TEST:STATUS:START?": "Error Detector",
    "ERRORDetector:BIT:TEST:TIME": "Error Detector",
    "ERRORDetector:BIT:TEST:TIME?": "Error Detector",
    "ERRORDetector:BITRate": "Error Detector",
    "ERRORDetector:CHANnel": "Error Detector",
    "ERRORDetector:CHARacter": "Error Detector",
    "ERRORDetector:CHARacter:TEST": "Error Detector",
    "ERRORDetector:CHARacter:TEST:RATE": "Error Detector",
    "ERRORDetector:CHARacter:TEST:RATE?": "Error Detector",
    "ERRORDetector:CHARacter:TEST:STATUS": "Error Detector",
    "ERRORDetector:CHARacter:TEST:STATUS?": "Error Detector",
    "ERRORDetector:CHARacter:TEST:TIME": "Error Detector",
    "ERRORDetector:CHARacter:TEST:TIME?": "Error Detector",
    "ERRORDetector:CHARacter?": "Error Detector",
    "ERRORDetector:DURATION:COUNt": "Error Detector",
    "ERRORDetector:DURATION:TIME:DAYS": "Error Detector",
    "ERRORDetector:DURATION:TIME:SECOnds": "Error Detector",
    "ERRORDetector:FILE:RECAll": "Error Detector",
    "ERRORDetector:FILE:SAVe": "Error Detector",
    "ERRORDetector:FRAME": "Error Detector",
    "ERRORDetector:FRAME?": "Error Detector",
    "ERRORDetector:FRAme:TEST": "Error Detector",
    "ERRORDetector:FRAme:TEST:RATE": "Error Detector",
    "ERRORDetector:FRAme:TEST:RATE?": "Error Detector",
    "ERRORDetector:FRAme:TEST:TIME": "Error Detector",
    "ERRORDetector:FRAme:TEST:TIME:DAYS": "Error Detector",
    "ERRORDetector:FRAme:TEST:TIME:DAYS?": "Error Detector",
    "ERRORDetector:FRAme:TEST:TIME?": "Error Detector",
    "ERRORDetector:MAXALIGNS": "Error Detector",
    "ERRORDetector:PATTERNNAME": "Error Detector",
    "ERRORDetector:PREset": "Error Detector",
    "ERRORDetector:PREset:APPLY": "Error Detector",
    "ERRORDetector:SIGnaltype": "Error Detector",
    "ERRORDetector:SKIPSETPRIMitive:STATE": "Error Detector",
    "ERRORDetector:STANdard": "Error Detector",
    "ERRORDetector:STATE": "Error Detector",
    "ERRORDetector:SYMBOL": "Error Detector",
    "ERRORDetector:SYMBOL:TEST": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:BITRate": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:BITRate?": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:RATE": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:RATE?": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:TIME": "Error Detector",
    "ERRORDetector:SYMBOL:TEST:TIME?": "Error Detector",
    "ERRORDetector:SYMBOL?": "Error Detector",
    "ERRORDetector:TIMEformat": "Error Detector",
    "EXPort:FILEName": "Hard copy",
    "EXPort:FORMat": "Hard copy",
    "EXPort:PALEtte": "Hard copy",
    "EXPort:READOuts": "Hard copy",
    "EXPort:VIEW": "Hard copy",
    "FASTAcq:HIACQRATE": "Acquisition",
    "FASTAcq:STATE": "Acquisition",
    "FILESystem:COPy": "File system",
    "FILESystem:CWD": "File system",
    "FILESystem:DELEte": "File system",
    "FILESystem:DIR": "File system",
    "FILESystem:DIR?": "File system",
    "FILESystem:MKDir": "File system",
    "FILESystem:PRInt": "File system",
    "FILESystem:READFile": "File system",
    "FILESystem:REName": "File system",
    "FILESystem:RMDir": "File system",
    "FILESystem:WRITEFile": "File system",
    "FLEXRAY:EOFTYPE": "Search and Mark",
    "FLEXRAY:HEADER:CRC": "Search and Mark",
    "FPANel:PRESS": "Miscellaneous",
    "HARDCopy:FILEName": "Hard copy",
    "HARDCopy:LAYout": "Hard copy",
    "HARDCopy:PALEtte": "Hard copy",
    "HARDCopy:PORT": "Hard copy",
    "HARDCopy:READOuts": "Hard copy",
    "HARDCopy:VIEW": "Hard copy",
    "HIStogram:BOX": "Histogram",
    "HIStogram:BOXPcnt": "Histogram",
    "HIStogram:COUNt": "Histogram",
    "HIStogram:DATa": "Histogram",
    "HIStogram:DATa?": "Histogram",
    "HIStogram:DISplay": "Histogram",
    "HIStogram:FUNCtion": "Histogram",
    "HIStogram:MODe": "Histogram",
    "HIStogram:SIZe": "Histogram",
    "HIStogram:SOUrce": "Histogram",
    "HIStogram:STATE": "Histogram",
    "HORizontal:ACQDURATION": "Horizontal",
    "HORizontal:ACQDURATION?": "Horizontal",
    "HORizontal:ACQLENGTH": "Horizontal",
    "HORizontal:ACQLENGTH?": "Horizontal",
    "HORizontal:DIGital:SAMPLERate:MAIn": "Horizontal",
    "HORizontal:DIGital:SAMPLERate:MAIn?": "Horizontal",
    "HORizontal:DIVisions": "Horizontal",
    "HORizontal:DIVisions?": "Horizontal",
    "HORizontal:FASTframe": "Horizontal",
    "HORizontal:FASTframe:COUNt": "Horizontal",
    "HORizontal:FASTframe:REF:FRAme": "Horizontal",
    "HORizontal:FASTframe:SELECTED:CH<x>": "Horizontal",
    "HORizontal:FASTframe:SELECTED:REF<x>": "Horizontal",
    "HORizontal:FASTframe:SIXteenbit": "Horizontal",
    "HORizontal:FASTframe:TIMEStamp:REF": "Horizontal",
    "HORizontal:FASTframe:TIMEStamp:REF?": "Horizontal",
    "HORizontal:FASTframe:TRACk": "Horizontal",
    "HORizontal:FASTframe:XZEro:ALL:REF<x>": "Horizontal",
    "HORizontal:FASTframe:XZEro:ALL:REF<x>?": "Horizontal",
    "HORizontal:FASTframe:XZEro:REF": "Horizontal",
    "HORizontal:FASTframe:XZEro:REF?": "Horizontal",
    "HORizontal:FASTframe?": "Horizontal",
    "HORizontal:MAIn": "Horizontal",
    "HORizontal:MAIn?": "Horizontal",
    "HORizontal:MODE:SAMPLERate": "Horizontal",
    "HORizontal:MODE:SCAle": "Horizontal",
    "HORizontal:POSition": "Horizontal",
    "HORizontal:ROLL": "Horizontal",
    "HORizontal[:MAIn]:DELay:POSition": "Horizontal",
    "HORizontal[:MAIn]:DELay:TIMe": "Horizontal",
    "IDNMultiscope:A": "Miscellaneous",
    "IDNMultiscope:A?": "Miscellaneous",
    "IDNMultiscope:B": "Miscellaneous",
    "IDNMultiscope:B?": "Miscellaneous",
    "IDNMultiscope:C": "Miscellaneous",
    "IDNMultiscope:C?": "Miscellaneous",
    "IDNMultiscope:D": "Miscellaneous",
    "IDNMultiscope:D?": "Miscellaneous",
    "LIMit:BEEP": "Limit Test",
    "LIMit:COMpare": "Limit Test",
    "LIMit:COMpare:CH<x>": "Limit Test",
    "LIMit:COMpare:MATH<x>": "Limit Test",
    "LIMit:COMpare:REF<x>": "Limit Test",
    "LIMit:EMail": "Limit Test",
    "LIMit:HARDCopy": "Limit Test",
    "LIMit:HIGHLIGHTHits": "Limit Test",
    "LIMit:HIGHLIGHTHits:RESet": "Limit Test",
    "LIMit:LOCk": "Limit Test",
    "LIMit:LOG": "Limit Test",
    "LIMit:SAVEWFM": "Limit Test",
    "LIMit:SAVEWFM:FILEName": "Limit Test",
    "LIMit:SRQ": "Limit Test",
    "LIMit:STATE": "Limit Test",
    "LIMit:STATus": "Limit Test",
    "LIMit:STATus?": "Limit Test",
    "LIMit:STOPOnviolation": "Limit Test",
    "LIMit:TEMPlate:SOUrce": "Limit Test",
    "LIMit:TEMPlate:STORe": "Limit Test",
    "LIMit:TEMPlate:TOLerance:VERTical": "Limit Test",
    "MARK:CREATE": "Search and Mark",
    "MARK:DELEte": "Search and Mark",
    "MARK:FREE": "Search and Mark",
    "MARK:FREE?": "Search and Mark",
    "MARK:SELECTED:END": "Search and Mark",
    "MARK:SELECTED:END?": "Search and Mark",
    "MARK:SELECTED:STARt": "Search and Mark",
    "MARK:SELECTED:STARt?": "Search and Mark",
    "MARK:SELECTED:ZOOm:POSition": "Search and Mark",
    "MARK:SELECTED:ZOOm:POSition?": "Search and Mark",
    "MASK:AUTOAdjust": "Mask",
    "MASK:AUTOAdjust:HDELTA": "Mask",
    "MASK:AUTOAdjust:VDELTA": "Mask",
    "MASK:AUTOSet:HPOS": "Mask",
    "MASK:AUTOSet:HSCAle": "Mask",
    "MASK:AUTOSet:MODe": "Mask",
    "MASK:AUTOSet:OFFSETAdj": "Mask",
    "MASK:AUTOSet:STANdard": "Mask",
    "MASK:AUTOSet:TRIGger": "Mask",
    "MASK:AUTOSet:VPOS": "Mask",
    "MASK:AUTOSet:VSCAle": "Mask",
    "MASK:COPy:USER": "Mask",
    "MASK:COUNt": "Mask",
    "MASK:COUNt:FAILURES": "Mask",
    "MASK:COUNt:FAILURES?": "Mask",
    "MASK:COUNt:HITS": "Mask",
    "MASK:COUNt:HITS?": "Mask",
    "MASK:COUNt:TESTS": "Mask",
    "MASK:COUNt:TESTS?": "Mask",
    "MASK:COUNt:TOTal": "Mask",
    "MASK:COUNt:TOTal?": "Mask",
    "MASK:COUNt:VIOLATIONS": "Mask",
    "MASK:COUNt:VIOLATIONS?": "Mask",
    "MASK:DISplay": "Mask",
    "MASK:FILTer": "Mask",
    "MASK:HIGHLIGHTHits": "Mask",
    "MASK:INVert": "Mask",
    "MASK:LOCk": "Mask",
    "MASK:MARgin:PERCent": "Mask",
    "MASK:MARgin:STATE": "Mask",
    "MASK:MASKPRE:HSCAle": "Mask",
    "MASK:MASKPRE:HTRIGPOS": "Mask",
    "MASK:MASKPRE:PRESAMPBITS": "Mask",
    "MASK:MASKPRE:RECOrdlength": "Mask",
    "MASK:MASKPRE:VOFFSet": "Mask",
    "MASK:MASKPRE:VPOS": "Mask",
    "MASK:MASKPRE:VSCAle": "Mask",
    "MASK:MASKPRE:WIDth": "Mask",
    "MASK:POLarity": "Mask",
    "MASK:SEG<m>": "Mask",
    "MASK:SEG<m>:NR_Pt": "Mask",
    "MASK:SEG<m>:NR_Pt?": "Mask",
    "MASK:SEG<m>:POINTS": "Mask",
    "MASK:STANdard": "Mask",
    "MASK:STOPOnviolation": "Mask",
    "MASK:TESt:DELay": "Mask",
    "MASK:TESt:HARDCopy": "Mask",
    "MASK:TESt:LOG:FAILure": "Mask",
    "MASK:TESt:REPeat": "Mask",
    "MASK:TESt:SAMple": "Mask",
    "MASK:TESt:SAMple:THReshold": "Mask",
    "MASK:TESt:SAVEWFM": "Mask",
    "MASK:TESt:SRQ:COMPLetion": "Mask",
    "MASK:TESt:STATE": "Mask",
    "MASK:TESt:STATUS": "Mask",
    "MASK:TESt:STATUS?": "Mask",
    "MASK:TESt:STOP:FAILure": "Mask",
    "MASK:TESt:THReshold": "Mask",
    "MASK:TESt:WAVEform": "Mask",
    "MASK:USER:AMPlitude": "Mask",
    "MASK:USER:BITRate": "Mask",
    "MASK:USER:HSCAle": "Mask",
    "MASK:USER:LABel": "Mask",
    "MASK:USER:PATTERNBITS": "Mask",
    "MASK:USER:RECOrdlength": "Mask",
    "MASK:USER:TRIGTOSAMP": "Mask",
    "MASK:USER:VOFFSet": "Mask",
    "MASK:USER:VPOS": "Mask",
    "MASK:USER:VSCAle": "Mask",
    "MASK:USER:WIDth": "Mask",
    "MATH<x>:DEFine": "Math",
    "MATH<x>:FILTer:MODe": "Math",
    "MATH<x>:FILTer:RISetime": "Math",
    "MATH<x>:LABel:NAMe": "Math",
    "MATH<x>:LABel:XPOS": "Math",
    "MATH<x>:LABel:YPOS": "Math",
    "MATH<x>:NUMAVg": "Math",
    "MATH<x>:SPECTral": "Math",
    "MATH<x>:SPECTral:REFLevel": "Math",
    "MATH<x>:SPECTral:SUPPress": "Math",
    "MATH<x>:SPECTral:WINdow": "Math",
    "MATH<x>:SPECTral?": "Math",
    "MATH<x>:THRESHold": "Math",
    "MATH<x>:UNITString": "Math",
    "MATH<x>:VERTical:AUTOSCale": "Math",
    "MATHArbflt<x>:FILepath": "Math",
    "MATHArbflt<x>:READFile": "Math",
    "MATHVAR:VAR<x>": "Math",
    "MEASUrement:GATing": "Measurement",
    "MEASUrement:IMMed": "Measurement",
    "MEASUrement:IMMed:DELay:EDGE2": "Measurement",
    "MEASUrement:IMMed:METHod": "Measurement",
    "MEASUrement:IMMed:NOISe": "Measurement",
    "MEASUrement:IMMed:REFLevel:METHod": "Measurement",
    "MEASUrement:IMMed:SOUrce<x>": "Measurement",
    "MEASUrement:IMMed:SOUrce<x>:SIGType": "Measurement",
    "MEASUrement:IMMed:UNIts": "Measurement",
    "MEASUrement:IMMed:UNIts?": "Measurement",
    "MEASUrement:IMMed?": "Measurement",
    "MEASUrement:MEAS<x>:DELay:EDGE<x>": "Measurement",
    "MEASUrement:MEAS<x>:MAXimum": "Measurement",
    "MEASUrement:MEAS<x>:MAXimum?": "Measurement",
    "MEASUrement:MEAS<x>:REFLevel": "Measurement",
    "MEASUrement:MEAS<x>:REFLevel?": "Measurement",
    "MEASUrement:MEAS<x>:SOUrce<x>": "Measurement",
    "MEASUrement:MEAS<x>:STATE": "Measurement",
    "MEASUrement:MEAS<x>:UNIts": "Measurement",
    "MEASUrement:MEAS<x>:UNIts?": "Measurement",
    "MEASUrement:METHod": "Measurement",
    "MEASUrement:NOISe": "Measurement",
    "MEASUrement:SOUrce<x>:SIGType": "Measurement",
    "MEASUrement:STATIstics:WEIghting": "Measurement",
    "MIL1553B:ERRTYPE": "Search and Mark",
    "MIL1553B:STATUS:BIT:BUSY": "Search and Mark",
    "MIL1553B:STATUS:BIT:ME": "Search and Mark",
    "MIL1553B:STATUS:BIT:TF": "Search and Mark",
    "NOTE. Not available on some models HORizontal:DIGital:RECOrdlength": "Horizontal",
    "NOTE. Not available on some models HORizontal:DIGital:RECOrdlength:MAIn": "Horizontal",
    "NOTE. Not available on some models HORizontal:DIGital:RECOrdlength:MAIn?": "Horizontal",
    "NOTE. Not available on some models HORizontal:DIGital:RECOrdlength?": "Horizontal",
    "NOTE. This trigger is available only with Option LSA installed TRIGger:A:I2C:ADDRess:MODe": "Low Speed Serial Trigger",
    "RATE5000, RATE6000, RATE6250} for error detection ERRORDetector:BITRate:VALue": "Error Detector",
    "RECAll:MASK": "Mask",
    "RECAll:SETUp": "Save and Recall",
    "RECAll:SETUp:DESKew": "Save and Recall",
    "RECAll:WAVEform": "Save and Recall",
    "REF<x>:HORizontal:POSition": "Vertical",
    "REF<x>:LABel": "Vertical",
    "REF<x>:LABel:NAMe": "Vertical",
    "REF<x>:LABel:XPOS": "Vertical",
    "REF<x>:LABel:YPOS": "Vertical",
    "REF<x>:LABel?": "Vertical",
    "REF<x>:THRESHold": "Digital",
    "REF<x>:VERTical:POSition": "Vertical",
    "REF<x>:VERTical:SCAle": "Vertical",
    "ROSc:OUT:FREQuency": "Miscellaneous",
    "ROSc:OUT:ULTRAsync": "Miscellaneous",
    "ROSc:SOUrce": "Miscellaneous",
    "ROSc:STATE": "Miscellaneous",
    "ROSc:STATE?": "Miscellaneous",
    "ROSc:TRACking": "Miscellaneous",
    "SAVEON:COUNt": "Save On",
    "SAVEON:COUNt?": "Save On",
    "SAVEON:FILE:AUTOInc": "Save On",
    "SAVEON:FILE:COUNt": "Save On",
    "SAVEON:FILE:DEST": "Save On",
    "SAVEON:FILE:NAME": "Save On",
    "SAVEON:FILE:TYPE": "Save On",
    "SAVEON:IMAGe": "Save On",
    "SAVEON:LIMit": "Save On",
    "SAVEON:MASK": "Save On",
    "SAVEON:NUMEvents": "Save On",
    "SAVEON:SETUP": "Save On",
    "SAVEON:TRIGger": "Save On",
    "SAVEON:WAVEform": "Save On",
    "SAVe:EVENTtable:BUS<x>": "Save and Recall",
    "SAVe:MARKS": "Save and Recall",
    "SAVe:MASK": "Mask",
    "SAVe:SETUp": "Save and Recall",
    "SAVe:WAVEform": "Save and Recall",
    "SAVe:WAVEform:DATa:STOP": "Save and Recall",
    "SEARCH:MARKALLevents": "Search and Mark",
    "SEARCH:SEARCH<x>": "Search and Mark",
    "SEARCH:SEARCH<x>:STATE": "Search and Mark",
    "SEARCH:SEARCH<x>:TOTAL": "Search and Mark",
    "SEARCH:SEARCH<x>:TOTAL?": "Search and Mark",
    "SEARCH:SEARCH<x>:TRIGger:A:TYPe": "Search and Mark",
    "SEARCH:STOP": "Search and Mark",
    "SELect:<wfm>": "Vertical",
    "SELect:B<x>": "Bus",
    "SELect:CH<x>": "Vertical",
    "SELect:CONTROl": "Vertical",
    "SELect:D<x>": "Digital",
    "SELect:DALL": "Digital",
    "SELect:DIGTraces:LISt": "Digital",
    "TEST:RESults": "Diagnostics",
    "TEST:RESults?": "Diagnostics",
    "TRIGger:A": "Trigger",
    "TRIGger:A:BUS:CAN:CONDition": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:DATa:FORMat": "Trigger",
    "TRIGger:A:BUS:DATa:VALue": "Trigger",
    "TRIGger:A:BUS:ETHERnet:DATa:OFFSet": "Trigger",
    "TRIGger:A:BUS:ETHERnet:DATa:SIZe": "Trigger",
    "TRIGger:A:BUS:ETHERnet:DATa:VALue": "Trigger",
    "TRIGger:A:BUS:ETHERnet:QTAG:VALue": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:CONDition": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:DATa:FORMat": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:DATa:OFFSet": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:FRAMEType": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:FLEXRAY:HEADER:INDBits": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:IDentifier:FORMat": "Trigger",
    "TRIGger:A:BUS:FLEXRAY:IDentifier:VALue": "Trigger",
    "TRIGger:A:BUS:LIN:DATa:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:MIL1553B:COMMAND:TRBit": "Trigger",
    "TRIGger:A:BUS:MIL1553B:DATA:FORMat": "Trigger",
    "TRIGger:A:BUS:MIL1553B:DATA:PARity": "Trigger",
    "TRIGger:A:BUS:MIL1553B:DATA:VALue": "Trigger",
    "TRIGger:A:BUS:MIL1553B:STATUS:BIT:BCR": "Trigger",
    "TRIGger:A:BUS:MIL1553B:STATUS:BIT:ME": "Trigger",
    "TRIGger:A:BUS:MIL1553B:STATUS:BIT:SRQ": "Trigger",
    "TRIGger:A:BUS:MIL1553B:STATUS:BIT:TF": "Trigger",
    "TRIGger:A:BUS:MIL1553B:TIME:LESSLimit": "Trigger",
    "TRIGger:A:BUS:MIL1553B:TIME:MORELimit": "Trigger",
    "TRIGger:A:BUS:MIL1553B:TIME:QUALifier": "Trigger",
    "TRIGger:A:BUS:PCIE:CONDition": "Trigger",
    "TRIGger:A:BUS:PCIE:DISParity": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:PCIE:FORMat": "Trigger",
    "TRIGger:A:BUS:RS232C:CONDition": "Trigger",
    "TRIGger:A:BUS:S8B10B:CONDition": "Trigger",
    "TRIGger:A:BUS:S8B10B:FORMat": "Trigger",
    "TRIGger:A:BUS:SOUrce": "Trigger",
    "TRIGger:A:BUS:SPI:CONDition": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:SPI:DATa:SIZe": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:ADDress:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:CHARacter:CHAR": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:CONDition": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:DATa:HIVALue": "Trigger",
    "TRIGger:A:BUS:USB:ENDPoint:FORMat": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:ENDPoint:HIVALue": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:ENDPoint:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:ERROR": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:ERRTYPE": "Trigger",
    "TRIGger:A:BUS:USB:HANDShaketype": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:PATtern:CHAR<x>": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:QUAlifier": "Trigger",
    "TRIGger:A:BUS:USB:SPECIALType": "Low Speed Serial Trigger",
    "TRIGger:A:BUS:USB:SPLIT:HUB:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:CONDition": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:DATa:DIRection": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:DATa:LEVel": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:DATa:SOUrce": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:DATa:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:FORMat": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:FRAMEtype": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:IDENTifier:MODe": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:IDENTifier:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:PROBE": "Low Speed Serial Trigger",
    "TRIGger:A:CAN:SPEed": "Low Speed Serial Trigger",
    "TRIGger:A:COMMunication:BITRate": "Trigger",
    "TRIGger:A:COMMunication:STANdard": "Trigger",
    "TRIGger:A:HOLDoff": "Trigger",
    "TRIGger:A:HOLDoff:TIMe": "Trigger",
    "TRIGger:A:HOLDoff?": "Trigger",
    "TRIGger:A:I2C:ADDRess:TYPe": "Low Speed Serial Trigger",
    "TRIGger:A:I2C:ADDRess:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:I2C:DATa:DIRection": "Low Speed Serial Trigger",
    "TRIGger:A:I2C:DATa:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:I2C:FORMat": "Low Speed Serial Trigger",
    "TRIGger:A:MODe": "Trigger",
    "TRIGger:A:PULse:PERiod:LOWLimit": "Trigger",
    "TRIGger:A:PULse:PERiod:QUAlify": "Trigger",
    "TRIGger:A:PULse:PERiod:WHEn": "Trigger",
    "TRIGger:A:RS232:BAUd": "Low Speed Serial Trigger",
    "TRIGger:A:RS232:FORMat": "Low Speed Serial Trigger",
    "TRIGger:A:RS232:PARity": "Low Speed Serial Trigger",
    "TRIGger:A:SERIAL:BITRate": "Trigger",
    "TRIGger:A:SERIAL:DATa:PATtern": "Trigger",
    "TRIGger:A:SPI:CONDition": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:DATa:MISO:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:DATa:MOSI:VALue": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:DATa:STARt": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:FORMat": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SCLK:ACTIVE": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SCLK:LEVel": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SCLK:SOUrce": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SS:ACTIVE": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SS:LEVel": "Low Speed Serial Trigger",
    "TRIGger:A:SPI:SS:SOUrce": "Low Speed Serial Trigger",
    "TRIGger:A:VIDeo:CUSTom": "Trigger",
    "TRIGger:A:VIDeo:CUSTom?": "Trigger",
    "TRIGger:A:VIDeo:FIELD": "Trigger",
    "TRIGger:A:VIDeo:POLarity": "Trigger",
    "TRIGger:A:VIDeo:SCAN": "Trigger",
    "TRIGger:A:VIDeo:SOUrce": "Trigger",
    "TRIGger:A:VIDeo:STANdard": "Trigger",
    "TRIGger:AUXLevel": "Trigger",
    "TRIGger:B": "Trigger",
    "TRIGger:B:BY": "Trigger",
    "TRIGger:B:EVENTS:COUNt": "Trigger",
    "TRIGger:B:PULse:GLItch:ENVelope": "Trigger",
    "TRIGger:B:PULse:PERiod:POLarity": "Trigger",
    "TRIGger:B:PULse:PERiod:WHEn": "Trigger",
    "TRIGger:B:RESET:ACCEPTCOUNT": "Trigger",
    "TRIGger:B:RESET:ACCEPTCOUNT?": "Trigger",
    "TRIGger:B:RESET:ACCEPTTIMEout": "Trigger",
    "TRIGger:B:RESET:RATIO": "Trigger",
    "TRIGger:B:RESET:RATIO?": "Trigger",
    "TRIGger:B:RESET:RATIOENable": "Trigger",
    "TRIGger:B:RESET:REJECTCOUNT": "Trigger",
    "TRIGger:B:RESET:REJECTCOUNT?": "Trigger",
    "TRIGger:B:RESET:REJECTTIMEout": "Trigger",
    "TRIGger:B:RESET:SOUrce": "Trigger",
    "TRIGger:B:RESET:STATE": "Trigger",
    "TRIGger:B:RESET:THReshold": "Trigger",
    "TRIGger:B:RESET:TIMEOut": "Trigger",
    "TRIGger:B:RESET:TRANsition": "Trigger",
    "TRIGger:B:SCAN:ENDevent": "Trigger",
    "TRIGger:B:SCAN:MODE": "Trigger",
    "TRIGger:B:TIMe": "Trigger",
    "TRIGger:ENHanced": "Trigger",
    "TRIGger:EQUation<1..1>": "Trigger",
    "TRIGger:LVLSrcpreference": "Trigger",
    "TRIGger:QUALification:BUS:FORMat": "Trigger",
    "TRIGger:SENSITivity": "Trigger",
    "TRIGger:STATE": "Trigger",
    "TRIGger:STATE?": "Trigger",
    "TRIGger:{A|B}:EDGE": "Trigger",
    "TRIGger:{A|B}:EDGE?": "Trigger",
    "TRIGger:{A|B}:LEVel": "Trigger",
    "TRIGger:{A|B}:LEVel:CH<x>": "Trigger",
    "TRIGger:{A|B}:LOGIc:CLAss": "Trigger",
    "TRIGger:{A|B}:LOGIc:FUNCtion": "Trigger",
    "TRIGger:{A|B}:LOGIc:PATtern": "Trigger",
    "TRIGger:{A|B}:LOGIc:PATtern?": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:CLOCk": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:CLOCk?": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:DATa": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:DATa:SOUrce": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:DATa?": "Trigger",
    "TRIGger:{A|B}:LOGIc:SETHold:HOLDTime": "Trigger",
    "TRIGger:{A|B}:LOGIc:STATE:CLOck:SOUrce": "Trigger",
    "TRIGger:{A|B}:PULse:CLAss": "Trigger",
    "TRIGger:{A|B}:PULse:GLItch:QUAlify": "Trigger",
    "TRIGger:{A|B}:PULse:RUNT:THReshold": "Trigger",
    "TRIGger:{A|B}:PULse:RUNT:THReshold?": "Trigger",
    "TRIGger:{A|B}:PULse:SOUrce": "Trigger",
    "TRIGger:{A|B}:PULse:TIMEOut:POLarity": "Trigger",
    "TRIGger:{A|B}:PULse:TIMEOut:QUAlify": "Trigger",
    "TRIGger:{A|B}:PULse:TRANsition:POLarity": "Trigger",
    "TRIGger:{A|B}:PULse:TRANsition:QUAlify": "Trigger",
    "TRIGger:{A|B}:PULse:TRANsition:WHEn": "Trigger",
    "TRIGger:{A|B}:PULse:WINdow": "Trigger",
    "TRIGger:{A|B}:PULse:WINdow:QUAlify": "Trigger",
    "TRIGger:{A|B}:PULse:WINdow:THReshold": "Trigger",
    "TRIGger:{A|B}:PULse:WINdow:THReshold?": "Trigger",
    "TRIGger:{A|B}:PULse:WINdow?": "Trigger",
    "TRIGger:{A|B}:READY": "Trigger",
    "TRIGger:{A|B}:READY?": "Trigger",
    "TRIGger:{A|B}:TYPe": "Trigger",
    "USBTMC:PRODUCTID:DECimal": "Miscellaneous",
    "USBTMC:PRODUCTID:DECimal?": "Miscellaneous",
    "VISual:AREA<x>": "Trigger",
    "VISual:AREA<x>:FLIP": "Trigger",
    "VISual:AREA<x>:HEIGHT": "Trigger",
    "VISual:AREA<x>:LABel": "Trigger",
    "VISual:AREA<x>:SHOWLOGic": "Trigger",
    "VISual:AREA<x>:SOURCE<1..1>": "Trigger",
    "VISual:AREA<x>:VERTICES": "Trigger",
    "VISual:AREA<x>?": "Trigger",
    "VISual:AREACOLOr": "Trigger",
    "VISual:DELETEAREA": "Trigger",
    "VISual:ENAble": "Trigger",
    "VISual:FILE:RECALL": "Trigger",
    "VISual:FILE:SAVE": "Trigger",
    "WFMInpre:BIT_Nr": "Waveform Transfer",
    "WFMInpre:BN_Fmt": "Waveform Transfer",
    "WFMInpre:BYT_Nr": "Waveform Transfer",
    "WFMInpre:BYT_Or": "Waveform Transfer",
    "WFMInpre:ENCdg": "Waveform Transfer",
    "WFMInpre:NR_FR": "Waveform Transfer",
    "WFMInpre:NR_FR?": "Waveform Transfer",
    "WFMInpre:NR_Pt": "Waveform Transfer",
    "WFMInpre:PT_Fmt": "Waveform Transfer",
    "WFMInpre:PT_Off": "Waveform Transfer",
    "WFMInpre:WFId": "Waveform Transfer",
    "WFMInpre:XINcr": "Waveform Transfer",
    "WFMInpre:XUNit": "Waveform Transfer",
    "WFMInpre:XZEro": "Waveform Transfer",
    "WFMInpre:YMUlt": "Waveform Transfer",
    "WFMInpre:YOFf": "Waveform Transfer",
    "WFMInpre:YUNit": "Waveform Transfer",
    "WFMInpre:YZEro": "Waveform Transfer",
    "WFMOutpre:BIT_Nr": "Waveform Transfer",
    "WFMOutpre:BN_Fmt": "Waveform Transfer",
    "WFMOutpre:BYT_Nr": "Waveform Transfer",
    "WFMOutpre:BYT_Or": "Waveform Transfer",
    "WFMOutpre:ENCdg": "Waveform Transfer",
    "WFMOutpre:NR_FR": "Waveform Transfer",
    "WFMOutpre:NR_FR?": "Waveform Transfer",
    "WFMOutpre:NR_Pt": "Waveform Transfer",
    "WFMOutpre:NR_Pt?": "Waveform Transfer",
    "WFMOutpre:PT_Fmt": "Waveform Transfer",
    "WFMOutpre:PT_Fmt?": "Waveform Transfer",
    "WFMOutpre:PT_ORder": "Waveform Transfer",
    "WFMOutpre:PT_ORder?": "Waveform Transfer",
    "WFMOutpre:PT_Off": "Waveform Transfer",
    "WFMOutpre:PT_Off?": "Waveform Transfer",
    "WFMOutpre:WFId": "Waveform Transfer",
    "WFMOutpre:WFId?": "Waveform Transfer",
    "WFMOutpre:XINcr": "Waveform Transfer",
    "WFMOutpre:XINcr?": "Waveform Transfer",
    "WFMOutpre:XUNit": "Waveform Transfer",
    "WFMOutpre:XUNit?": "Waveform Transfer",
    "WFMOutpre:XZEro": "Waveform Transfer",
    "WFMOutpre:XZEro?": "Waveform Transfer",
    "WFMOutpre:YMUlt": "Waveform Transfer",
    "WFMOutpre:YMUlt?": "Waveform Transfer",
    "WFMOutpre:YOFf": "Waveform Transfer",
    "WFMOutpre:YOFf?": "Waveform Transfer",
    "WFMOutpre:YUNit": "Waveform Transfer",
    "WFMOutpre:YUNit?": "Waveform Transfer",
    "WFMOutpre:YZEro": "Waveform Transfer",
    "WFMOutpre:YZEro?": "Waveform Transfer",
    "ZOOm:GRAticule:SIZE": "Zoom",
    "ZOOm:HORizontal:POSition": "Zoom",
    "ZOOm:HORizontal:SCAle": "Zoom",
    "ZOOm:MATH<x>:HORizontal:POSition": "Zoom",
    "ZOOm:MODe": "Zoom",
    "ZOOm:REF<x>:HORizontal:POSition": "Zoom",
    "ZOOm:SCROLL:LOCk": "Zoom",
    "ZOOm:SCROLL:SPEED": "Zoom",
    "ZOOm:STATE": "Zoom",
    "ZOOm:VERTical:POSition": "Zoom",
    "ZOOm:VERTical:SCAle": "Zoom",
    "ZOOm:ZOOM<x>": "Zoom",
    "ZOOm:ZOOM<x>:<wfm>:DISplay": "Zoom",
    "ZOOm:ZOOM<x>:<wfm>:HORizontal:SCAle": "Zoom",
    "ZOOm:ZOOM<x>:<wfm>:VERTical:POSition": "Zoom",
    "ZOOm:ZOOM<x>:<wfm>:VERTical:SCAle": "Zoom",
    "ZOOm:ZOOM<x>:STATE": "Zoom",
}

# Group descriptions (if available)
COMMAND_GROUPS = {
    "Acquisition": {
        "name": "Acquisition",
        "description": "",  # Add description if available
        "commands": 18  # Number of commands
    },
    "Alias": {
        "name": "Alias",
        "description": "",  # Add description if available
        "commands": 7  # Number of commands
    },
    "Bus": {
        "name": "Bus",
        "description": "",  # Add description if available
        "commands": 52  # Number of commands
    },
    "Calibration": {
        "name": "Calibration",
        "description": "",  # Add description if available
        "commands": 8  # Number of commands
    },
    "Cursor": {
        "name": "Cursor",
        "description": "",  # Add description if available
        "commands": 36  # Number of commands
    },
    "Diagnostics": {
        "name": "Diagnostics",
        "description": "",  # Add description if available
        "commands": 38  # Number of commands
    },
    "Digital": {
        "name": "Digital",
        "description": "",  # Add description if available
        "commands": 11  # Number of commands
    },
    "Display control": {
        "name": "Display control",
        "description": "",  # Add description if available
        "commands": 22  # Number of commands
    },
    "E-mail": {
        "name": "E-mail",
        "description": "",  # Add description if available
        "commands": 20  # Number of commands
    },
    "Error Detector": {
        "name": "Error Detector",
        "description": "",  # Add description if available
        "commands": 62  # Number of commands
    },
    "File system": {
        "name": "File system",
        "description": "",  # Add description if available
        "commands": 11  # Number of commands
    },
    "Hard copy": {
        "name": "Hard copy",
        "description": "",  # Add description if available
        "commands": 11  # Number of commands
    },
    "Histogram": {
        "name": "Histogram",
        "description": "",  # Add description if available
        "commands": 11  # Number of commands
    },
    "Horizontal": {
        "name": "Horizontal",
        "description": "",  # Add description if available
        "commands": 34  # Number of commands
    },
    "Limit Test": {
        "name": "Limit Test",
        "description": "",  # Add description if available
        "commands": 21  # Number of commands
    },
    "Low Speed Serial Trigger": {
        "name": "Low Speed Serial Trigger",
        "description": "",  # Add description if available
        "commands": 48  # Number of commands
    },
    "Mask": {
        "name": "Mask",
        "description": "",  # Add description if available
        "commands": 72  # Number of commands
    },
    "Math": {
        "name": "Math",
        "description": "",  # Add description if available
        "commands": 18  # Number of commands
    },
    "Measurement": {
        "name": "Measurement",
        "description": "",  # Add description if available
        "commands": 24  # Number of commands
    },
    "Miscellaneous": {
        "name": "Miscellaneous",
        "description": "",  # Add description if available
        "commands": 20  # Number of commands
    },
    "Save On": {
        "name": "Save On",
        "description": "",  # Add description if available
        "commands": 14  # Number of commands
    },
    "Save and Recall": {
        "name": "Save and Recall",
        "description": "",  # Add description if available
        "commands": 10  # Number of commands
    },
    "Search and Mark": {
        "name": "Search and Mark",
        "description": "",  # Add description if available
        "commands": 23  # Number of commands
    },
    "Trigger": {
        "name": "Trigger",
        "description": "",  # Add description if available
        "commands": 154  # Number of commands
    },
    "Vertical": {
        "name": "Vertical",
        "description": "",  # Add description if available
        "commands": 91  # Number of commands
    },
    "Waveform Transfer": {
        "name": "Waveform Transfer",
        "description": "",  # Add description if available
        "commands": 59  # Number of commands
    },
    "Zoom": {
        "name": "Zoom",
        "description": "",  # Add description if available
        "commands": 17  # Number of commands
    },
}