# Calibration commands
calibration = [
    "*CAL?",
    "CALibrate?",
    "CALibrate:INTERNal",
    "CALibrate:INTERNal:STARt",
    "CALibrate:INTERNal:STATus?",
    "CALibrate:PWRUpstatus?",
    "TOUCHSCReen:CALibrate",
    "TOUCHSCReen:STATe"
]

# Callout commands
callout = [
    "CALLOUTS:ADDNew",
    "CALLOUTS:CALLOUT<x>:BOOKMark:SOURCE",
    "CALLOUTS:CALLOUT<x>:BOOKMark:XPOS",
    "CALLOUTS:CALLOUT<x>:COLOR",
    "CALLOUTS:CALLOUT<x>:DISPLAYPOSition:X",
    "CALLOUTS:CALLOUT<x>:DISPLAYPOSition:Y",
    "CALLOUTS:CALLOUT<x>:FONT:BOLD",
    "CALLOUTS:CALLOUT<x>:FONT:ITALIC",
    "CALLOUTS:CALLOUT<x>:FONT:SIZE",
    "CALLOUTS:CALLOUT<x>:FONT:TYPE",
    "CALLOUTS:CALLOUT<x>:FONT:UNDERLine",
    "CALLOUTS:CALLOUT<x>:TEXT",
    "CALLOUTS:CALLOUT<x>:TYPE",
    "CALLOUTS:DELete"
]

# Cursor commands - extracted from the text
cursor = [
    "DISplay:MATHFFTView<x>:CURSor:ASOUrce?",
    "DISplay:MATHFFTView<x>:CURSor:BSOUrce?",
    "DISplay:MATHFFTView<x>:CURSor:DDT?",
    "DISplay:MATHFFTView<x>:CURSor:FUNCtion",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:AUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:BPOSition",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:BUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:DELTa?",
    "DISplay:MATHFFTView<x>:CURSor:MODe",
    "DISplay:MATHFFTView<x>:CURSor:ONEOVERDELTATVALUE?",
    "DISplay:MATHFFTView<x>:CURSor:ROLOCATION",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:AXPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:AYPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:BXPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:BYPOSition",
    "DISplay:MATHFFTView<x>:CURSor:STATE",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:AUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:BPOSition",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:BUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:DELTa?",
    "DISplay:MATHFFTView<x>:CURSor:WAVEform:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:WAVEform:BPOSition",
    "DISplay:PLOTView<x>:CURSor:ASOUrce?",
    "DISplay:PLOTView<x>:CURSor:BSOUrce?",
    "DISplay:PLOTView<x>:CURSor:DDT?",
    "DISplay:PLOTView<x>:CURSor:FUNCtion",
    "DISplay:PLOTView<x>:CURSor:HBArs:APOSition",
    "DISplay:PLOTView<x>:CURSor:HBArs:AUNIts?",
    "DISplay:PLOTView<x>:CURSor:HBArs:BPOSition",
    "DISplay:PLOTView<x>:CURSor:HBArs:BUNIts?",
    "DISplay:PLOTView<x>:CURSor:HBArs:DELTa?",
    "DISplay:PLOTView<x>:CURSor:MODe",
    "DISplay:PLOTView<x>:CURSor:ONEOVERDELTATVALUE?",
    "DISplay:PLOTView<x>:CURSor:ROLOCATION",
    "DISplay:PLOTView<x>:CURSor:SCREEN:AXPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:AYPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:BXPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:BYPOSition",
    "DISplay:PLOTView<x>:CURSor:SPLITMODE",
    "DISplay:PLOTView<x>:CURSor:STATE",
    "DISplay:PLOTView<x>:CURSor:VBArs:APOSition",
    "DISplay:PLOTView<x>:CURSor:VBArs:BPOSition",
    "DISplay:PLOTView<x>:CURSor:VBArs:DELTa?",
    "DISplay:PLOTView<x>:CURSor:VBArs:UNIts?",
    "DISplay:PLOTView<x>:CURSor:WAVEform:APOSition",
    "DISplay:PLOTView<x>:CURSor:WAVEform:BPOSition",
    "DISplay:REFFFTView<x>:CURSor:ASOUrce?",
    "DISplay:REFFFTView<x>:CURSor:BSOUrce?",
    "DISplay:REFFFTView<x>:CURSor:DDT?",
    "DISplay:REFFFTView<x>:CURSor:FUNCtion",
    "DISplay:REFFFTView<x>:CURSor:HBArs:APOSition",
    "DISplay:REFFFTView<x>:CURSor:HBArs:AUNIts?",
    "DISplay:REFFFTView<x>:CURSor:HBArs:BPOSition",
    "DISplay:REFFFTView<x>:CURSor:HBArs:BUNIts?",
    "DISplay:REFFFTView<x>:CURSor:HBArs:DELTa?",
    "DISplay:REFFFTView<x>:CURSor:MODe",
    "DISplay:REFFFTView<x>:CURSor:ONEOVERDELTATVALUE?",
    "DISplay:REFFFTView<x>:CURSor:ROLOCATION",
    "DISplay:REFFFTView<x>:CURSor:SCREEN:AXPOSition",
    "DISplay:REFFFTView<x>:CURSor:SCREEN:AYPOSition",
    "DISplay:REFFFTView<x>:CURSor:SCREEN:BXPOSition",
    "DISplay:REFFFTView<x>:CURSor:SCREEN:BYPOSition",
    "DISplay:REFFFTView<x>:CURSor:SPLITMODE",
    "DISplay:REFFFTView<x>:CURSor:STATE",
    "DISplay:REFFFTView<x>:CURSor:VBArs:APOSition",
    "DISplay:REFFFTView<x>:CURSor:VBArs:BPOSition",
    "DISplay:REFFFTView<x>:CURSor:VBArs:DELTa?",
    "DISplay:REFFFTView<x>:CURSor:VBArs:UNIts?",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:AHPOSition?",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:APOSition",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:AVPOSition?",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:BHPOSition?",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:BPOSition",
    "DISplay:REFFFTView<x>:CURSor:WAVEform:BVPOSition?",
    "DISplay:SPECView<x>:CURSor:CURSOR:ANOISEDensity?",
    "DISplay:SPECView<x>:CURSor:CURSOR:ASOUrce",
    "DISplay:SPECView<x>:CURSor:CURSOR:BNOISE?",
    "DISplay:SPECView<x>:CURSor:CURSOR:BSOUrce",
    "DISplay:SPECView<x>:CURSor:CURSOR:HBArs:APOSition",
    "DISplay:SPECView<x>:CURSor:CURSOR:HBArs:AUNIts?",
    "DISplay:SPECView<x>:CURSor:CURSOR:HBArs:BPOSition",
    "DISplay:SPECView<x>:CURSor:CURSOR:HBArs:BUNIts?",
    "DISplay:SPECView<x>:CURSor:CURSOR:READout",
    "DISplay:SPECView<x>:CURSor:CURSOR:SPLITMODE",
    "DISplay:SPECView<x>:CURSor:CURSOR:STATE",
    "DISplay:SPECView<x>:CURSor:CURSOR:VBArs:APOSition",
    "DISplay:SPECView<x>:CURSor:CURSOR:VBArs:BPOSition",
    "DISplay:SPECView<x>:CURSor:CURSOR:VBArs:UNIts?",
    "DISplay:SPECView<x>:CURSor:CURSOR:WAVEform:APOSition",
    "DISplay:SPECView<x>:CURSor:CURSOR:WAVEform:BPOSition",
    "DISplay:WAVEView<x>:CURSor?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:ASOUrce",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:BSOUrce",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:DDT?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:FUNCtion",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:APOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:AUNIts?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:BPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:BUNIts?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:HBArs:DELTa?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:MODe",
    "DISplay:WAVEView:CURSor:CURSOR1:ROLOCATION",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:ONEOVERDELTATVALUE?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:AXPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:AYPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:BXPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:SCREEN:BYPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:SPLITMODE",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:STATE",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:APOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:BPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:DELTa?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:VBArs:UNIts?",
    "DISplay:WAVEView<x>:CURSor:CURSOR:WAVEform:ALL:Values?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:WAVEform:APOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR:WAVEform:AVPOSition?",
    "DISplay:WAVEView<x>:CURSor:CURSOR<x>:WAVEform:BPOSition",
    "DISplay:WAVEView<x>:CURSor:CURSOR:WAVEform:BVPOSition?"
]

print("Calibration:", len(calibration))
print("Callout:", len(callout))
print("Cursor:", len(cursor))
print("\nTotal:", len(calibration) + len(callout) + len(cursor))










