# History commands
history = [
    "TSTamptable:ADDNew",
    "TSTamptable:DELETE",
    "TSTamptable:LIST?"
]

# Horizontal commands
horizontal = [
    "ACQuire:NUMFRAMESACQuired?",
    "HORizontal?",
    "HORizontal:ACQDURATION?",
    "HORizontal:DELay:MODe",
    "HORizontal:DELay:TIMe",
    "HORizontal:DIVisions?",
    "HORizontal:FASTframe?",
    "HORizontal:FASTframe:COUNt",
    "HORizontal:FASTframe:MAXFRames?",
    "HORizontal:FASTframe:MULtipleframes:MODe",
    "HORizontal:FASTframe:REF:FRAme",
    "HORizontal:FASTframe:REF:INCLUde",
    "HORizontal:FASTframe:SELECTED",
    "HORizontal:FASTframe:STATE",
    "HORizontal:FASTframe:SUMFrame",
    "HORizontal:FASTframe:SUMFrame:STATE",
    "HORizontal:FASTframe:TIMEStamp:REFerence?",
    "HORizontal:FASTframe:TIMEStamp:SELECTED?",
    "HORizontal:FASTframe:TIMEStamp:DELTa?",
    "HORizontal:FASTframe:TIMEStamp:ALL?",
    "HORizontal:FASTframe:XZEro:ALL?",
    "HORizontal:FASTframe:XZEro:REF?",
    "HORizontal:FASTframe:XZEro:SELECTED?",
    "HORizontal:HISTory:CSTAts",
    "HORizontal:HISTory:OVERlay",
    "HORizontal:HISTory:REF:ACQ",
    "HORizontal:HISTory:REF:INClude",
    "HORizontal:HISTory:SELected",
    "HORizontal:HISTory:STATe",
    "HORizontal:HISTory:TIMEStamp:DELTa?",
    "HORizontal:HISTory:TIMEStamp:REFerence?",
    "HORizontal:HISTory:TIMEStamp:SELECTED?",
    "HORizontal:MAIn:INTERPRatio?",
    "HORizontal:MODe",
    "HORizontal:MODe:AUTOmatic:FASTAcq:RECOrdlength:MAXimum:VALue",
    "HORizontal:MODe:AUTOmatic:FASTAcq:RECOrdlength:MAXimum:ZOOMOVERride",
    "HORizontal:MODe:MANual:CONFIGure",
    "HORizontal:MODe:RECOrdlength",
    "HORizontal:MODe:SAMPLERate",
    "HORizontal:MODe:SCAle",
    "HORizontal:POSition",
    "HORizontal:PREViewstate?",
    "HORizontal:RECOrdlength",
    "HORizontal:ROLL?",
    "HORizontal:SAMPLERate",
    "HORizontal:SAMPLERate:ANALYZemode:MINimum:OVERRide",
    "HORizontal:SAMPLERate:ANALYZemode:MINimum:VALue",
    "HORizontal:SCAle"
]

# IMDA commands
imda = [
    "CUSTOMTABle:ADDNew",
    "CUSTOMTABle:DELete",
    "CUSTOMTABle:LIST?",
    "MEASUrement:ADDMEAS",
    "MEASUrement:AUTOset",
    "MEASUrement:HIGHLEVel:CONFIGuration",
    "MEASUrement:HIGHLEVel:EDGEQUALifier",
    "MEASUrement:HIGHLEVel:INLOWPass:FREQ",
    "MEASUrement:HIGHLEVel:INLOWPass:SPEC",
    "MEASUrement:HIGHLEVel:L2LTOL2N",
    "MEASUrement:HIGHLEVel:LINESelected",
    "MEASUrement:HIGHLEVel:OUTEDGEQUALifier",
    "MEASUrement:HIGHLEVel:OUTLOWPass:FREQ",
    "MEASUrement:HIGHLEVel:OUTLOWPass:SPEC",
    "MEASUrement:HIGHLEVel:OUTL2LTOL2N",
    "MEASUrement:HIGHLEVel:OUTLINESelected",
    "MEASUrement:HIGHLEVel:OUTSOURCE",
    "MEASUrement:HIGHLEVel:OUTWIRing",
    "MEASUrement:HIGHLEVel:SOURCE",
    "MEASUrement:HIGHLEVel:WIRing",
    "MEASUrement:MEAS<x>:COVer",
    "MEASUrement:MEAS<x>:CUSTOMLIMITSFile",
    "MEASUrement:MEAS<x>:CYCLemode",
    "MEASUrement:MEAS<x>:EDGEQUALifier",
    "MEASUrement:MEAS<x>:EDGEQUALONE",
    "MEASUrement:MEAS<x>:EDGEQUALTWO",
    "MEASUrement:MEAS<x>:FILTERRANGEFROM",
    "MEASUrement:MEAS<x>:FILTERRANGETO",
    "MEASUrement:MEAS<x>:FILTers:LOWPass:FREQ",
    "MEASUrement:MEAS<x>:FILTers:LOWPass:SPEC",
    "MEASUrement:MEAS<x>:FREQ",
    "MEASUrement:MEAS<x>:FUNDCURRent",
    "MEASUrement:MEAS<x>:HARMONICSCLass",
    "MEASUrement:MEAS<x>:HARMONICSSOURce",
    "MEASUrement:MEAS<x>:HARMONICSStd",
    "MEASUrement:MEAS<x>:HARMONICSUNits",
    "MEASUrement:MEAS<x>:HIGHLEVel:CONFIGuration",
    "MEASUrement:MEAS<x>:HIGHLEVel:L2LTOL2N",
    "MEASUrement:MEAS<x>:HIGHLEVel:LINESelected",
    "MEASUrement:MEAS<x>:HIGHLEVel:OUTL2LTOL2N",
    "MEASUrement:MEAS<x>:HIGHLEVel:OUTLINESelected",
    "MEASUrement:MEAS<x>:HIGHLEVel:OUTWIRing",
    "MEASUrement:MEAS<x>:HIGHLEVel:USEGLOBAL",
    "MEASUrement:MEAS<x>:HIGHLEVel:WIRing",
    "MEASUrement:MEAS<x>:HTORque",
    "MEASUrement:MEAS<x>:HVOLtage",
    "MEASUrement:MEAS<x>:INPUTPOwer",
    "MEASUrement:MEAS<x>:LINESelected",
    "MEASUrement:MEAS<x>:LTORque",
    "MEASUrement:MEAS<x>:LVOLtage",
    "MEASUrement:MEAS<x>:MECH:EINDexz",
    "MEASUrement:MEAS<x>:MECH:GRATio",
    "MEASUrement:MEAS<x>:MECH:MUNits",
    "MEASUrement:MEAS<x>:MECH:PPAirs",
    "MEASUrement:MEAS<x>:MECH:PPRotation",
    "MEASUrement:MEAS<x>:MECH:STYPe",
    "MEASUrement:MEAS<x>:ODDEVen",
    "MEASUrement:MEAS<x>:OFILters:LOWPass:FREQ",
    "MEASUrement:MEAS<x>:OUTFILTers:LOWPass:SPEC",
    "MEASUrement:MEAS<x>:OSANgle",
    "MEASUrement:MEAS<x>:OUTEDGEQUALifier",
    "MEASUrement:MEAS<x>:OUTFILTers:LOWPass:FREQ",
    "MEASUrement:MEAS<x>:OUTFILTers:LOWPass:SPEC",
    "MEASUrement:MEAS<x>:POWERFACtor",
    "MEASUrement:MEAS<x>:SEQuence",
    "MEASUrement:MEAS<x>:SIGNALFREQUEncy",
    "MEASUrement:MEAS<x>:SOURCE",
    "MEASUrement:MEAS<x>:STYPe",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:MEAN?",
    "MEASUrement:MEAS<x>:SUNits",
    "MEASUrement:MEAS<x>:TCONstant",
    "MEASUrement:MEAS<x>:TDRPreset",
    "MEASUrement:MEAS<x>:TMEThod",
    "MEASUrement:MEAS<x>:TYPe",
    "MEASUrement:MECH:EINDexz",
    "MEASUrement:MECH:GRATio",
    "MEASUrement:MECH:MUNits",
    "MEASUrement:MECH:PPAirs",
    "MEASUrement:MECH:PPRotation",
    "MEASUrement:MECH:SOUrce<x>",
    "MEASUrement:MECH:STYPe"
]

# Mask commands
mask = [
    "EYEMASK:MASK<x>:COUNt:HITS?",
    "EYEMASK:MASK<x>:COUNt:SEG<y>:HITS?",
    "EYEMASK:MASK<x>:CREATor?",
    "EYEMASK:MASK<x>:ENAbled",
    "EYEMASK:MASK<x>:MASKfile",
    "EYEMASK:MASK<x>:MASKOffset:HORizontal:AUTOfit?",
    "EYEMASK:MASK<x>:TESt:SAMple:THReshold",
    "EYEMASK:MASK<x>:TESt:STATUS?",
    "MASK:DELete",
    "MASK:MASK<x>:COUNT?",
    "MASK:MASK<x>:COUNT:HITS?",
    "MASK:MASK<x>:DEFinedby",
    "MASK:MASK<x>:DISplay",
    "MASK:MASK<x>:LIST?",
    "MASK:MASK<x>:SEG<x>:POINTS",
    "MASK:MASK<x>:SEG<x>:COUNT:HITS?",
    "MASK:MASK<x>:SOUrce",
    "MASK:MASK<x>:TESt:CTHReshold",
    "MASK:MASK<x>:TESt:STATE",
    "MASK:MASK<x>:TESt:STATUS?",
    "MASK:MASK<x>:TESt:THReshold",
    "MASK:MASK<x>:TOLerance:HABSolute",
    "MASK:MASK<x>:TOLerance:HORizontal",
    "MASK:MASK<x>:TOLerance:UPDatenow",
    "MASK:MASK<x>:TOLerance:VABSolute",
    "MASK:MASK<x>:TOLerance:VERTical",
    "MASK:MASK<x>:TTYPe",
    "MASK:TESt:WAVEforms",
    "RECAll:MASK"
]

# Math commands
math = [
    "DISplay:SELect:MATH",
    "DISplay:WAVEView<x>:MATH:MATH<x>:STATE",
    "DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:SCAle",
    "MATH:ADDNew",
    "MATHArbflt<x>:FILepath",
    "MATH:DELete",
    "MATH:LIST?",
    "MATH:MATH<x>:ARINC429A:SUPPortedfields",
    "MATH:MATH<x>:AUDIO:SUPPortedfields",
    "MATH:MATH<x>:AUTOETHERnet:SUPPortedfields",
    "MATH:MATH<x>:AVG:MODE",
    "MATH:MATH<x>:AVG:WEIGht",
    "MATH:MATH<x>:CAN:SUPPortedfields",
    "MATH:MATH<x>:CXPI:SUPPortedfields",
    "MATH:MATH<x>:ESPI:SUPPortedfields",
    "MATH:MATH<x>:ETHERCATSUPPortedfields",
    "MATH:MATH<x>:ETHERnet:SUPPortedfields",
    "MATH:MATH<x>:EUSB:SUPPortedfields",
    "MATH:MATH<x>:FILTer:CFReq",
    "MATH:MATH<x>:FILTer:DELay",
    "MATH:MATH<x>:FILTer:DESIgn",
    "MATH:MATH<x>:FILTer:HCFReq",
    "MATH:MATH<x>:FILTer:INFo?",
    "MATH:MATH<x>:FILTer:LCFReq",
    "MATH:MATH<x>:FILTer:LOAD",
    "MATH:MATH<x>:FILTer:LOAD:RESPonse",
    "MATH:MATH<x>:FILTer:ORDer",
    "MATH:MATH<x>:FILTer:PRIPple",
    "MATH:MATH<x>:FILTer:RESPonse",
    "MATH:MATH<x>:FILTer:ROFactor",
    "MATH:MATH<x>:FILTer:SATTenuation",
    "MATH:MATH<x>:FILTer:SAVe",
    "MATH:MATH<x>:FILTer:SAVe:RESPonse",
    "MATH:MATH<x>:FILTer:SDEViation",
    "MATH:MATH<x>:FILTer:SDURation",
    "MATH:MATH<x>:FILTer:SOURce",
    "MATH:MATH<x>:FILTer:SYMBols",
    "MATH:MATH<x>:FILTer:TWIDth",
    "MATH:MATH<x>:FILTer:TYPe",
    "MATH:MATH<x>:FLEXray:SUPPortedfields",
    "MATH:MATH<x>:FUNCtion",
    "MATH:MATH<x>:I2C:SUPPortedfields",
    "MATH:MATH<x>:I3C:SUPPortedfields",
    "MATH:MATH<x>:INTERpolation",
    "MATH:MATH<x>:LABel:COLor",
    "MATH:MATH<x>:LABel:FONT:BOLD",
    "MATH:MATH<x>:LABel:FONT:ITALic",
    "MATH:MATH<x>:LABel:FONT:SIZE",
    "MATH:MATH<x>:LABel:FONT:TYPE",
    "MATH:MATH<x>:LABel:FONT:UNDERline",
    "MATH:MATH<x>:LABel:XPOS",
    "MATH:MATH<x>:LABel:YPOS",
    "MATH:MATH<x>:DEFine",
    "MATH:MATH<x>:GATing",
    "MATH:MATH<x>:LABel:NAMe",
    "MATH:MATH<x>:LIN:SUPPortedfields",
    "MATH:MATH<x>:MDIO:SUPPortedfields",
    "MATH:MATH<x>:MIL1553B:SUPPortedfields",
    "MATH:MATH<x>:ONEWIRe:SUPPortedfields",
    "MATH:MATH<x>:PARallel:SUPPortedfields",
    "MATH:MATH<x>:PSIFIVe:SUPPortedfields",
    "MATH:MATH<x>:RS232C:SUPPortedfields",
    "MATH:MATH<x>:SDLC:SUPPortedfields",
    "MATH:MATH<x>:SENT:SUPPortedfields",
    "MATH:MATH<x>:SIGNeddata",
    "MATH:MATH<x>:SMBUS:SUPPortedfields",
    "MATH:MATH<x>:SOUrce<x>",
    "MATH:MATH<x>:SPACEWIRe:SUPPortedfields",
    "MATH:MATH<x>:SPECTral:HORZ",
    "MATH:MATH<x>:SPECTral:MAG",
    "MATH:MATH<x>:SPECTral:PHASE",
    "MATH:MATH<x>:SPECTral:SOUrce",
    "MATH:MATH<x>:SPECTral:SUPPress",
    "MATH:MATH<x>:SPECTral:SUPPress:VALue",
    "MATH:MATH<x>:SPECTral:TYPE",
    "MATH:MATH<x>:SPECTral:UNWRap",
    "MATH:MATH<x>:SPECTral:UNWRap:DEGrees",
    "MATH:MATH<x>:SPECTral:WINdow",
    "MATH:MATH<x>:SPI:SUPPortedfields",
    "MATH:MATH<x>:SPMI:SUPPortedfields",
    "MATH:MATH<x>:SVID:SUPPortedfields",
    "MATH:MATH<x>:TYPe",
    "MATH:MATH<x>:USB:SUPPortedfields",
    "MATH:MATH<x>:VUNIT"
]

print("History:", len(history))
print("Horizontal:", len(horizontal))
print("IMDA:", len(imda))
print("Mask:", len(mask))
print("Math:", len(math))
print("\nTotal:", len(history) + len(horizontal) + len(imda) + len(mask) + len(math))










