# Digital commands
digital = [
    "CH<x>_DALL:LABel:COLor",
    "CH<x>_DALL:LABel:FONT:BOLD",
    "CH<x>_DALL:LABel:FONT:ITALic",
    "CH<x>_DALL:LABel:FONT:SIZE",
    "CH<x>_DALL:LABel:FONT:TYPE",
    "CH<x>_DALL:LABel:FONT:UNDERline",
    "CH<x>_DALL:LABel:NAMe",
    "CH<x>_D<x>:LABel:COLor",
    "CH<x>_D<x>:LABel:FONT:BOLD",
    "CH<x>_D<x>:LABel:FONT:ITALic",
    "CH<x>_D<x>:LABel:FONT:SIZE",
    "CH<x>_D<x>:LABel:FONT:TYPE",
    "CH<x>_D<x>:LABel:FONT:UNDERline",
    "CH<x>_D<x>:LABel:NAMe",
    "REF<x>_DALL:LABel:COLor",
    "REF<x>_DALL:LABel:FONT:BOLD",
    "REF<x>_DALL:LABel:FONT:ITALic",
    "REF<x>_DALL:LABel:FONT:SIZE",
    "REF<x>_DALL:LABel:FONT:TYPE",
    "REF<x>_DALL:LABel:FONT:UNDERline",
    "REF<x>_DALL:LABel:NAMe",
    "REF<x>_DALL:LABel:XPOS",
    "REF<x>_DALL:LABel:YPOS",
    "REF<x>_D<x>:LABel:COLor",
    "REF<x>_D<x>:LABel:FONT:BOLD",
    "REF<x>_D<x>:LABel:FONT:ITALic",
    "REF<x>_D<x>:LABel:FONT:SIZE",
    "REF<x>_D<x>:LABel:FONT:TYPE",
    "REF<x>_D<x>:LABel:FONT:UNDERline",
    "REF<x>_D<x>:LABel:NAMe",
    "REF<x>_D<x>:LABel:XPOS",
    "REF<x>_D<x>:LABel:YPOS",
    "DIGGRP<x>:D<x>:THReshold"
]

# DPM commands
dpm = [
    "MEASUrement:AUTOset",
    "MEASUrement:MEAS<x>:EDGEQUALifier",
    "MEASUrement:MEAS<x>:INPUTLEVel",
    "MEASUrement:MEAS<x>:MAXVoltage",
    "MEASUrement:MEAS<x>:OUTPUT<x>VOLTage",
    "MEASUrement:MEAS<x>:PFREquency",
    "MEASUrement:MEAS<x>:PTHReshold",
    "MEASUrement:MEAS<x>:REConstwfm",
    "MEASUrement:MEAS<x>:REFVOLTAGE<x>Val",
    "MEASUrement:MEAS<x>:RFREquency",
    "MEASUrement:MEAS<x>:RIPPLEFREQ<x>Val",
    "MEASUrement:MEAS<x>:RRANGE",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:MAXimum?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:MEAN?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:MINimum?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:PK2PK?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:POPUlation?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:ALLAcqs:STDDev?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:MAXimum?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:MEAN?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:MINimum?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:PK2PK?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:POPUlation?",
    "MEASUrement:MEAS<x>:SUBGROUP:RESUlts:CURRentacq:STDDev?",
    "MEASUrement:MEAS<x>:WAITTime",
    "PLOT:PLOT<x>:RAILNUM"
]

# Display control commands - this is a large group, extracting from the text
display = [
    "DISplay?",
    "DISplay:{CH<x>|MATH<x>|REF<x>}:INVERTColor",
    "DISplay:{CH<x>|MATH<x>|REF<x>}:NORMALColor",
    "DISplay:COLors",
    "DISplay:GLObal:B<x>:STATE",
    "DISplay:GLObal:CH<x>:STATE",
    "DISplay:GLObal:MATH<x>:STATE",
    "DISplay:GLObal:PLOT<x>:STATE",
    "DISplay:GLObal:REF<x>:STATE",
    "DISplay:INTENSITy?",
    "DISplay:INTENSITy:BACKLight",
    "DISplay:INTENSITy:BACKLight:AUTODim:ENAble",
    "DISplay:INTENSITy:BACKLight:AUTODim:TIMe",
    "DISplay:MATHFFTView<x>:AUTOScale",
    "DISplay:MATHFFTView<x>:MATH:MATH<x>:STATE",
    "DISplay:MATHFFTView<x>:CURSor:ASOUrce?",
    "DISplay:MATHFFTView<x>:CURSor:BSOUrce?",
    "DISplay:MATHFFTView<x>:CURSor:DDT?",
    "DISplay:MATHFFTView<x>:CURSor:FUNCtion",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:AUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:BPOSition",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:BUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:HBArs:DELTa?",
    "DISplay:MATHFFTView<x>:CURSor:MODe",
    "DISplay:MATHFFTView<x>:CURSor:ONEOVERDELTATVALUE?",
    "DISplay:MATHFFTView<x>:CURSor:ROLOCATION",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:AXPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:AYPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:BXPOSition",
    "DISplay:MATHFFTView<x>:CURSor:SCREEN:BYPOSition",
    "DISplay:MATHFFTView<x>:CURSor:STATE",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:AUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:BPOSition",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:BUNIts?",
    "DISplay:MATHFFTView<x>:CURSor:VBArs:DELTa?",
    "DISplay:MATHFFTView<x>:CURSor:WAVEform:APOSition",
    "DISplay:MATHFFTView<x>:CURSor:WAVEform:BPOSition",
    "DISplay:MATHFFTView<x>:GRIDlines",
    "DISplay:MATHFFTView<x>:MATH:MATH<x>:STATE",
    "DISplay:MATHFFTView<x>:ZOOM:XAXIS:FROM",
    "DISplay:MATHFFTView<x>:ZOOM:XAXIS:TO",
    "DISplay:MATHFFTView<x>:ZOOM:YAXIS:FROM",
    "DISplay:MATHFFTView<x>:ZOOM:YAXIS:TO",
    "DISplay:MATHFFTView<x>:XAXIS:SCALE",
    "DISplay:MATHFFTView<x>:YAXIS:SCALE",
    "DISplay:MEAS<x>:NAVIgate:TYPE",
    "DISplay:PERSistence",
    "DISplay:PERSistence:RESET",
    "DISplay:PLOTView<x>:AUTOScale",
    "DISplay:PLOTView<x>:CURSor:ASOUrce?",
    "DISplay:PLOTView<x>:CURSor:BSOUrce?",
    "DISplay:PLOTView<x>:CURSor:DDT?",
    "DISplay:PLOTView<x>:CURSor:FUNCtion",
    "DISplay:PLOTView<x>:CURSor:HBArs:APOSition",
    "DISplay:PLOTView<x>:CURSor:HBArs:BPOSition",
    "DISplay:PLOTView<x>:CURSor:HBArs:AUNIts?",
    "DISplay:PLOTView<x>:CURSor:HBArs:BUNIts?",
    "DISplay:PLOTView<x>:CURSor:HBArs:DELTa?",
    "DISplay:PLOTView<x>:CURSor:MODe",
    "DISplay:PLOTView<x>:CURSor:ONEOVERDELTATVALUE?",
    "DISplay:PLOTView<x>:CURSor:ROLOCATION",
    "DISplay:PLOTView<x>:CURSor:SCREEN:AXPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:AYPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:BXPOSition",
    "DISplay:PLOTView<x>:CURSor:SCREEN:BYPOSition",
    "DISplay:PLOTView<x>:GRIDlines",
    "DISplay:PLOTView<x>:XAXIS:SCALE",
    "DISplay:PLOTView<x>:YAXIS:SCALE",
    "DISplay:PLOTView<x>:ZOOM:XAXIS:FROM",
    "DISplay:PLOTView<x>:ZOOM:XAXIS:TO",
    "DISplay:PLOTView<x>:ZOOM:YAXIS:FROM",
    "DISplay:PLOTView<x>:ZOOM:YAXIS:TO",
    "DISplay:REFFFTView<x>:AUTOScale",
    "DISplay:REFFFTView<x>:GRIDlines",
    "DISplay:REFFFTView<x>:REF:REF<x>:STATE",
    "DISplay:REFFFTView<x>:XAXIS:SCALE",
    "DISplay:SELect:BUS",
    "DISplay:SELect:MATH",
    "DISplay:SELect:REFerence",
    "DISplay:SELect:SOUrce",
    "DISplay:SELect:SPECView<x>:SOUrce",
    "DISplay:SPECView<x>:CH<x>:VERTical:POSition",
    "DISplay:SPECView<x>:CH<x>:VERTical:SCAle",
    "DISplay:SPECView<x>:GRAticule",
    "DISplay:SPECView<x>:HORZ",
    "DISplay:SPECView<x>:INTENSITy:GRATicule",
    "DISplay:SPECView<x>:INTENSITy:WAVEform",
    "DISplay:SPECView<x>:VIEWStyle",
    "DISplay:SELect:VIEW",
    "DISplay:SELect:WAVEView<x>:SOUrce",
    "DISplay:VARpersist",
    "DISplay:WAVEform",
    "DISplay:WAVEView<x>:BUS:B<x>:STATE",
    "DISplay:WAVEView<x>:BUS:B<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:CH<x>:STATE",
    "DISplay:WAVEView<x>:CH<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:CH<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:CH<x>_DALL:STATE",
    "DISplay:WAVEView<x>:CH<x>_DALL:VERTical:POSition",
    "DISplay:WAVEView<x>:CH<x>_D<x>:STATE",
    "DISplay:WAVEView<x>:FILTer",
    "DISplay:WAVEView<x>:GRAticule",
    "DISplay:WAVEView<x>:INTENSITy:GRATicule",
    "DISplay:WAVEView<x>:INTENSITy:WAVEform",
    "DISplay:WAVEView<x>:MATH:MATH<x>:AUTOScale",
    "DISplay:WAVEView<x>:MATH:MATH<x>:STATE",
    "DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:MATH:MATH<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:PLOT:PLOT<x>:AUTOScale",
    "DISplay:WAVEView<x>:PLOT:PLOT<x>:STATE",
    "DISplay:WAVEView<x>:PLOT:PLOT<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:PLOT:PLOT<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:REF<x>_DALL:FRAMe",
    "DISplay:WAVEView<y>:REF:REF<x>:FRAMe",
    "DISplay:WAVEView<x>:REF:REF<x>:STATE",
    "DISplay:WAVEView<x>:REF:REF<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:REF:REF<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:RF_FREQuency<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:RF_FREQuency<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:RF_MAGnitude<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:RF_MAGnitude<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:RF_PHASe<x>:VERTical:POSition",
    "DISplay:WAVEView<x>:RF_PHASe<x>:VERTical:SCAle",
    "DISplay:WAVEView<x>:STYle",
    "DISplay:WAVEView<x>:VIEWStyle",
    "DISplay:WAVEView:GRIDTYPE",
    "DISplay:WAVEView<x>:BUS:B<x>:STATE",
    "DISplay:WAVEView<x>:BUS:B<x>:VERTical:POSition"
]

# DVM commands
dvm = [
    "DVM",
    "DVM:AUTORange",
    "DVM:MEASUrement:FREQuency?",
    "DVM:MEASUrement:HIStory:AVErage?",
    "DVM:MEASUrement:HIStory:MAXimum?",
    "DVM:MEASUrement:HIStory:MINImum?",
    "DVM:MEASUrement:INFMAXimum?",
    "DVM:MEASUrement:INFMINimum?",
    "DVM:MEASUrement:VALue?",
    "DVM:MODe",
    "DVM:SOUrce",
    "DVM:TRIGger:FREQuency:COUNTer"
]

# Ethernet commands
ethernet = [
    "ETHERnet:DHCPbootp",
    "ETHERnet:DNS:IPADDress",
    "ETHERnet:DOMAINname",
    "ETHERnet:ENET:ADDress?",
    "ETHERnet:GATEWay:IPADDress",
    "ETHERnet:IPADDress",
    "ETHERnet:LXI:LAN:RESET",
    "ETHERnet:LXI:LAN:SERVICENAMe",
    "ETHERnet:LXI:LAN:STATus?",
    "ETHERnet:NAME",
    "ETHERnet:NETWORKCONFig",
    "ETHERnet:PING",
    "THERnet:PING:STATus?",
    "ETHERnet:SUBNETMask"
]

# File system commands
filesystem = [
    "FILESystem?",
    "FILESystem:COPy",
    "FILESystem:CWD",
    "FILESystem:DELEte",
    "FILESystem:DIR?",
    "FILESystem:HOMEDir?",
    "FILESystem:LDIR?",
    "FILESystem:MKDir",
    "FILESystem:MOUNT:DRIVE",
    "FILESystem:MOUNT:TEKDrive",
    "FILESystem:READFile",
    "FILESystem:REName",
    "FILESystem:RMDir",
    "FILESystem:TEKDrive:CODE?",
    "FILESystem:TEKDrive:CODE:EXPirytime?",
    "FILESystem:TEKDrive:CODE:STATus?",
    "FILESystem:UNMOUNT:DRIve",
    "FILESystem:UNMOUNT:TEKDrive",
    "FILESystem:WRITEFile"
]

# Histogram commands
histogram = [
    "HISTogram:ADDNew",
    "HISTogram:DELete",
    "HISTogram:DELETEALL",
    "HISTogram:HISTogram<x>:BOX",
    "HISTogram:HISTogram<x>:BSTate",
    "HISTogram:HISTogram<x>:DATa?",
    "HISTogram:HISTogram<x>:DISPlay",
    "HISTogram:HISTogram<x>:FUNCtion",
    "HISTogram:HISTogram<x>:MEASurement:COUNt",
    "HISTogram:HISTogram<x>:MEASurement:HITS",
    "HISTogram:HISTogram<x>:MEASurement:MAX",
    "HISTogram:HISTogram<x>:MEASurement:MEAN",
    "HISTogram:HISTogram<x>:MEASurement:MEDian",
    "HISTogram:HISTogram<x>:MEASurement:MIN",
    "HISTogram:HISTogram<x>:MEASurement:MODE",
    "HISTogram:HISTogram<x>:MEASurement:ONESigma",
    "HISTogram:HISTogram<x>:MEASurement:PHITs",
    "HISTogram:HISTogram<x>:MEASurement:PK2PK",
    "HISTogram:HISTogram<x>:MEASurement:RESUlts?",
    "HISTogram:HISTogram<x>:MEASurement:STDDev",
    "HISTogram:HISTogram<x>:MEASurement:THRSigma",
    "HISTogram:HISTogram<x>:MEASurement:TWOSigma",
    "HISTogram:HISTogram<x>:SAVe",
    "HISTogram:HISTogram<x>:SIZe",
    "HISTogram:HISTogram<x>:SOUrce",
    "HISTogram:HISTogram<x>:STATE",
    "HISTogram:HISTogram<x>:TRANsparency",
    "HISTogram:LIST?"
]

print("Digital:", len(digital))
print("DPM:", len(dpm))
print("Display:", len(display))
print("DVM:", len(dvm))
print("Ethernet:", len(ethernet))
print("File System:", len(filesystem))
print("Histogram:", len(histogram))
print("\nTotal:", len(digital) + len(dpm) + len(display) + len(dvm) + len(ethernet) + len(filesystem) + len(histogram))










